### ISSUE TITLE
gsutil : OSError,  Not a directory, can't trace, debug, fix 

### ISSUE THREAD

**Issue by HemangChothani** [GoogleCloudPlatform/gsutil#1058]
@sergeykish has opend an issue in [python-storage](https://github.com/googleapis/python-storage/issues/181) repo , but it's related to gsutil so I am opening the issue here for better response. 

**Environment details**

    $ uname -a
    Linux notebook 5.7.2-arch1-1 googleapis/google-cloud-python#1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64        GNU/Linux
    $ python --version
    Python 3.8.3
    $ cd /opt/google-cloud-sdk/
    $ cat VERSION 
    293.0.0

**Steps to reproduce**

1. make foo object and foo path to the object
2. rsync to local folder
    OSError: Not a directory

I know I can't make file and directory with same name in directory. I'd like to make it encode node type in name or maybe skip it. Unfortunately I can't trace where it throws error. I've tried python -mpdb ..., it does not catch. Does it spawn another process? How can I debug it?

**Code example**

    $ echo foo > foo
    $ echo bar > bar
    $ gsutil cp foo gs://sergeykish.com/foo
    $ gsutil cp bar gs://sergeykish.com/foo/bar
    $ gsutil rsync -r gs://sergeykish.com/ .

WARNING: gsutil rsync uses hashes when modification time is not available at
both the source and destination. Your crcmod installation isn't using the
module's C extension, so checksumming will run very slowly. If this is your
first rsync since updating gsutil, this rsync can take significantly longer than
usual. For help installing the extension, please see "gsutil help crcmod".

Building synchronization state...
Starting synchronization...
Copying gs://sergeykish.com/foo...
Copying gs://sergeykish.com/foo/bar...                                          
OSError: Not a directory. 8.0 B]                       

**Stack trace**

No stack trace.

PDB traces to Exec

    (Pdb) import sys
    (Pdb) old_sys_exit = sys.exit
    (Pdb) def new_sys_exit (value) : breakpoint()
    (Pdb) sys.exit = new_sys_exit
    (Pdb) b new_sys_exit
    End of file
    (Pdb) c
    ...
    OSError: Not a directory..6 KiB]                                                
    --Return--
    > <stdin>(1)new_sys_exit()->None
    (Pdb) where
    ...
    -> """A convenience wrapper for starting gsutil."""
      /opt/google-cloud-sdk/bin/bootstrapping/gsutil.py(102)main()
    -> bootstrapping.ExecutePythonTool('platform/gsutil', 'gsutil', *args)
      /opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py(107)ExecutePythonTool()
    -> _ExecuteTool(
      /opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py(199)_ExecuteTool()
    -> execution_utils.Exec(args + sys.argv[1:], env=_GetToolEnv())
      /opt/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py(357)Exec()
    -> sys.exit(ret_val)
      > <stdin>(1)new_sys_exit()->None

**Comment by thomasmaclean** [comment]
The lack of a stack trace is odd, but the error is expected given the situation. Google Cloud Storage doesn't support true folders, so you can get away with having an object with the same name as a "folder" (object `foo` vs the implied folder `foo` in `foo/bar`) whereas that's not something you could do in most operating systems, hence the error.

This is probably something we could handle better than we do now so I'll leave this open.

**Comment by sergeykish** [comment]
@thomasmaclean yes, I understand, GCP namespace is flat, expanded as directories on local. I've thought of either not expanding path or encoding directories. Start with exception, work out but all I got was silent error. Looking at gsutil now I am not sure I can do it.

With @HemangChothani help I can see trace

```
Copying gs://sergeykish.com/foo/bar...
DEBUG: Exception stack trace: B]                                                
    Traceback (most recent call last):
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 620, in _RunNamedCommandAndHandleExceptions
        return command_runner.RunNamedCommand(command_name,
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 411, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1661, in RunCommand
        self.Apply(_RsyncFunc,
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1514, in Apply
        self._SequentialApply(func, args_iterator, exception_handler, caller_id,
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1586, in _SequentialApply
        worker_thread.PerformTask(task, self)
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/command.py", line 2306, in PerformTask
        results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1427, in _RsyncFunc
        copy_result = copy_helper.PerformCopy(
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/utils/copy_helper.py", line 3868, in PerformCopy
        return _DownloadObjectToFile(src_url,
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/utils/copy_helper.py", line 3036, in _DownloadObjectToFile
        download_file_name, need_to_unzip = _GetDownloadFile(dst_url,
      File "/opt/google-cloud-sdk/platform/gsutil/gslib/utils/copy_helper.py", line 2328, in _GetDownloadFile
        fp = open(download_file_name, 'ab')
    NotADirectoryError: [Errno 20] Not a directory: './foo/bar_.gstmp'
    
OSError: Not a directory.
```

So it checks `os.path.exists` but does not check `os.path.isdir`. Interestingly same file contains

```
def CheckForDirFileConflict(exp_src_url, dst_url):
  """Checks whether copying exp_src_url into dst_url is not possible.

     This happens if a directory exists in local file system where a file
     needs to go or vice versa. In that case we print an error message and
     exits. Example: if the file "./x" exists and you try to do:
       gsutil cp gs://mybucket/x/y .
     the request can't succeed because it requires a directory where
     the file x exists.
```

which should catch this error.
