### ISSUE TITLE
AttributeError: 'CommandException' object has no attribute 'information'

### ISSUE THREAD

**Issue by bw2** [GoogleCloudPlatform/gsutil#1075]
Seeing this error after adding -n option to gsutil -m cp.  Running gsutil v4.52 and Python 2.7.16.

```
Traceback (most recent call last):
  File "/Users/weisburd/google-cloud-sdk/platform/gsutil/gslib/utils/arg_helper.py", line 35, in GetArgumentsAndOptions
    'testexceptiontraces', 'trace-token=', 'perf-trace-token='
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/getopt.py", line 95, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/getopt.py", line 195, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/getopt.py", line 211, in short_has_arg
    raise GetoptError(_('option -%s not recognized') % opt, opt)
getopt.GetoptError: option -n not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/weisburd/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 65, in <module>
    opts, args = GetArgumentsAndOptions()
  File "/Users/weisburd/google-cloud-sdk/platform/gsutil/gslib/utils/arg_helper.py", line 38, in GetArgumentsAndOptions
    raise CommandException(e.msg)
gslib.exception.CommandException: CommandException: option -n not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/weisburd/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/Users/weisburd/google-cloud-sdk/platform/gsutil/gsutil.py", line 122, in RunMain
    import gslib.__main__
  File "/Users/weisburd/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 67, in <module>
    reason = e.reason if e.information else 'CommandException: %s' % e.reason
AttributeError: 'CommandException' object has no attribute 'information'
```

**Comment by ecchochan** [comment]
I come across this issue `getopt.GetoptError: option -n not recognized`
I found out the correct syntax for using `-n` is:
```bash
gsutil -m cp -n ./data gs://somewhere
```
Note that the `-n` is after `cp` 😢 

For the `AttributeError`, a fix is proposed!
