### ISSUE TITLE
gsutil failing with incorrect AccessDenied error when trying to interoperate with s3 bucket

### ISSUE THREAD

**Issue by bmkessler** [GoogleCloudPlatform/gsutil#1162]
Problem you have encountered:

We have objects in an s3 bucket that are shared with us and we do not have full ListObjects access on the bucket.  Since Nov. 24th we are getting 403 AccessDenied errors when trying to download these objects using gsutil.  This is without any changes on our end, so I am not sure if Amazon changed something about their API at that time.

What you expected to happen:

Previously, we had been using

`gsutil -m rsync -r s3://amazon-bucket/amazon-prefix gs://gcs-bucket`

to sync these files with no issues.

Steps to reproduce:

Setup objects in s3 in a bucket and grant read permission to those objects without ListObjects permissions on the bucket and attempt to transfer them.

Other information (workarounds you have tried, documentation consulted, etc):

Note, I have confirmed that the correct credentials are still being used.  I can easily access the files using aws-cli, which is using boto3.

Also, I am able to access the files using boto 2.49.0 directly, e.g.

```python
from boto.s3.connection import S3Connection

conn = S3Connection('key_id', 'secret_key')
bucket = conn.get_bucket('amazon-bucket', validate=False)  # validate=False to avoid initial ListObjects call

for x in bucket.list(prefix='amazon-prefix'):
  print(x)

from boto.s3.key import Key

key = Key(bucket, 'object')
key.get_contents_to_filename('local_file')
```
So the issue appears to be in how gsutil is using boto to attempt the transfer.

We are using

gsutil version -l
gsutil version: 4.55
checksum: adebf7d276641651e3345d12aca978c0 (OK)
boto version: 2.49.0
python version: 3.7.5
...

Note:

`gsutil ls s3://amazon-bucket/amazon-prefix`

has no issues listing all objects with that prefix that are accessible to those credentials.

But any attempt to copy a specific object.

`gsutil cp s3://amazon-bucket/amazon-prefix/object .`

Fails with the same 403 AccessDenied error.

Running with debug logging.

`gsutil -DD cp s3://amazon-bucket/amazon-prefix/object .` indicates the the issue is in boto_translation.py

```
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/usr/local/gcloud/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 704, in _PerformResumableDownload
        hash_algs=hash_algs)
    TypeError: get_file() got an unexpected keyword argument 'hash_algs'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/gcloud/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 578, in GetObjectMedia
        hash_algs=hash_algs)
      File "/usr/local/gcloud/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 710, in _PerformResumableDownload
        override_num_retries=0)
      File "/usr/local/gcloud/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/key.py", line 1502, in get_file
        query_args=None)
      File "/usr/local/gcloud/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/key.py", line 1534, in _get_file_internal
        override_num_retries=override_num_retries)
      File "/usr/local/gcloud/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/key.py", line 358, in open
        override_num_retries=override_num_retries)
      File "/usr/local/gcloud/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/key.py", line 318, in open_read
        self.resp.reason, body)
    boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
```

So, now, going back and attempting to use that `get_file` API I get the same 403 error, which is really weird, because, looking at boto source

`key.get_contents_to_filename('local_file')`

Just does
```
with open('local_file', 'wb') as fp:
   key.get_contents_to_file(fp)
```

which then calls `key.get_file`
 
But if I call just `get_contents_to_file` as above instead of the successful `get_contents_to_filename` it also throws the AccessDenied error even though `get_contents_to_filename` is just a convenience wrapper over the `get_contents_to_file` underlying call so the underlying `get_contents_to_file` call should work too.

Feel free to close this if this is some underlying issue in `boto` that `gsutil` can't handle.

**Comment by bmkessler** [comment]
This appears to be an issue with the vendored boto dependency implicitly using version IDs when none were supplied.

https://github.com/gsutil-mirrors/boto/blob/cae713dd771bc918650efc1f2d0bf52c9e1a6a1c/boto/s3/key.py#L1521-L1525

```
        # If a version_id is passed in, use that.  If not, check to see
        # if the Key object has an explicit version_id and, if so, use that.
        # Otherwise, don't pass a version_id query param.
        if version_id is None:
            version_id = self.version_id
```

Explicit should read implicit in that comment as it was extracted from a prior response header.

I'll close this and move the issue over there.
