### ISSUE TITLE
CONTENT_DOWNLOAD_MISMATCH

### ISSUE THREAD

**Issue by tw1t611** [GoogleCloudPlatform/gsutil#1337]
I ran
```bash
gsutil -m setmeta -h "Cache-control:public, max-age=259200" gs://ari-motors-2-uploads
```
and get the following error when downloading the images through `@google-cloud/storage`:
```bash
strapi_1    | RequestError: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.
strapi_1    |     at PassThrough.onComplete (/srv/app/node_modules/@google-cloud/storage/build/src/file.js:1044:43)
strapi_1    |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
strapi_1    |   code: 'CONTENT_DOWNLOAD_MISMATCH'
strapi_1    | }
```
The file is later passed to sharp, which throw this error:
```bash
strapi_1    | [Error: Input buffer contains unsupported image format]
```

image download code:
```js
  const options = {
    destination: destFilename,
  };

  try {
    await storage.bucket(bucketName).file(filepath).download(options);
  } catch (error) {
    console.log(error);
```
The exact same code did work before executing the command.
The command didn't cause an error when running it the first time about two months ago.

Example file (public url):
https://storage.googleapis.com/ari-motors-2-uploads/05_ARI_145_Seitenansicht_vorn_rechts_00b43df2d0/05_ARI_145_Seitenansicht_vorn_rechts_00b43df2d0.jpg

**Comment by thomasmaclean** [comment]
This appears to be a bug in `@google-cloud/storage`, as I haven't found anywhere else where that error occurs. Meta changes shouldn't have any impact on hash calculation, yet that's what appears to happen with `@google-cloud/storage`.

**Comment by tw1t611** [comment]
Yes, I can confirm that it's working after redeployment.
ref: https://github.com/googleapis/nodejs-storage/issues/1596

Thanks for you help.
