### ISSUE TITLE
gsutil rsync fails with `Caught non-retryable exception - aborting rsync`

### ISSUE THREAD

**Issue by nerusnayleinad** [GoogleCloudPlatform/gsutil#1356]
We have some files in GCS that we need to have them synchronized with S3, in AWS, but when I run `gsutil rsync`, it fails with `Caught non-retryable exception - aborting rsync`.

What we need to do is to run rsync every day so any files that has changed in GCS gets synchronized with AWS. When I run the command for the first time it copies the files correctly, but when I run it next time it fails.

So, this is the error I get when I run the command bucket vs bucket. Then I debugged it (with -D), and it looks like it fails on a specific file, which is directly in the bucket (no in a folder). The debug error message is the following:

```
 crc32c: 'YW2ZwA=='
 generation: 1605913220800799
 md5Hash: 'uDEOva2LJsCKzE7U6vv0DQ=='
 name: 'file.jar'
 size: 10903598
 timeCreated: datetime.datetime(2020, 11, 20, 23, 0, 20, 800000, tzinfo=<apitools.base.protorpclite.util.TimeZoneOffset object at 0x7f7daf39df98>)>]
 prefixes: []>
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 639, in _RunNamedCommandAndHandleExceptions
        user_project=user_project)
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 410, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1674, in RunCommand
        diff_iterator = _DiffIterator(self, src_url, dst_url)
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1007, in __init__
        raise CommandException('Caught non-retryable exception - aborting rsync')
    gslib.exception.CommandException: CommandException: Caught non-retryable exception - aborting rsync
    
CommandException: Caught non-retryable exception - aborting rsync
```

What I did next is to run the commnd agaist that specific file, and this is the error I get:

```
 items: [<Object
 acl: []
 name: 'file.jar'>]
 prefixes: []>
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 639, in _RunNamedCommandAndHandleExceptions
        user_project=user_project)
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 410, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1642, in RunCommand
        src_url = self._InsistContainer(self.args[0], False)
      File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1625, in _InsistContainer
        'slash to specify the directory.' % url_str)
    gslib.exception.CommandException: CommandException: arg (gs://BUCKET-NAME/FILE.jar) does not name a directory, bucket, or bucket subdir.
    If there is an object with the same path, please add a trailing
    slash to specify the directory.
    
CommandException: arg (gs://BUCKET-NAME/FILE.jar) does not name a directory, bucket, or bucket subdir.
If there is an object with the same path, please add a trailing
slash to specify the directory.
```

The file name is `SOMETHING-SOMETHING-2.0.0-SNAPSHOT.jar`, so there are no special characters.

gsutil version: 4.65
boto version: 2.49.0
python: 3.7.3

I am not being able to go any further.

**Comment by knyttl** [comment]
🙏  this has been pain :/

**Comment by chetanamacherla1** [comment]
Any update on this?

**Comment by antouanbg** [comment]
Hi guys, any solution - I have same problem today! Any help?

**Comment by nerusnayleinad** [comment]
My specific issue was that our client had object names that were conflicting with `gsutil rsync`: [https://cloud.google.com/storage/docs/naming-objects](https://cloud.google.com/storage/docs/naming-objects)

In that scenario, if you have way too many objects, there is no solution. Out client had over a million objects, and it was impossible to change the names of the ones that were conflicting.

I used rclone, which by the way is an amazing tool for this task. It has been written in go (unlike gsutil, which is python), so all the memory management was flawless.

**Comment by JShollaj** [comment]
Personally, I had a careless mistake that led me to that error. 
First I ran:

`gsutil -m rsync -r -d -n gs://old_bucket s3://new_bucket`

Then I checked that I needed to configure the aws cli within the gcloud cli (both required the setting up the credentials and security ID). Next, I re-ran the code above and confirmed the files would get copied. 

As a final step I ran:

`gsutil -m rsync -r -d gs://old_bucket s3://new_bucket`

**Comment by danyill** [comment]
I know this is stale but it was an early search hit.

In case it helps someone else, I found that somehow my login credentials had been invalidated. I guess they had been like that for years and something changed in Google's infrastructure. I updated to a more recent version of `gsutil` and did a `gcloud auth login`.

After this synchronisation worked correctly.

The command I was using was to synchronise between a local disk and a cloud bucket:

`gsutil -m rsync -e -C -P -r <some local drive> gs://<some bucket>`
