### ISSUE TITLE
No module named 'importlib.resources' on gsutil 5.7 and python 3.5

### ISSUE THREAD

**Issue by svbatalov** [GoogleCloudPlatform/gsutil#1477]
Hello.

Starting on 2022-03-03 gsutil started failing with the following error:
```sh
# ./gsutil/gsutil
Traceback (most recent call last):
  File "/root/gsutil/third_party/certifi/certifi/core.py", line 14, in <module>
    from importlib.resources import path as get_path, read_text
ImportError: No module named 'importlib.resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/root/gsutil/gsutil.py", line 151, in RunMain
    import gslib.__main__
  File "/root/gsutil/gslib/__main__.py", line 83, in <module>
    import httplib2
  File "/root/gsutil/third_party/httplib2/python3/httplib2/__init__.py", line 123, in <module>
    from httplib2 import certs
  File "/root/gsutil/third_party/httplib2/python3/httplib2/certs.py", line 8, in <module>
    from certifi import where as certifi_where
  File "/root/gsutil/third_party/certifi/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/root/gsutil/third_party/certifi/certifi/core.py", line 46, in <module>
    Resource = Union[str, "os.PathLike"]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'PathLike'
```
This happens on python 3.5, while 3.8 works fine. The date coincides with the [release](https://github.com/GoogleCloudPlatform/gsutil/blob/master/CHANGES.md) of v5.7. Version 5.6 installed according to [these instructions](https://cloud.google.com/storage/docs/gsutil/addlhelp/ContributingCodetogsutil) works fine.

**Comment by dilipped** [comment]
Thanks for reporting! The team is aware of the issue and is working on addressing it in the next release. A workaround would be to use Python 3.5.3 or higher or rollback to v5.6
