### ISSUE TITLE
gsutil fails doing seeks on sequential inputs

### ISSUE THREAD

**Issue by pstemari** [GoogleCloudPlatform/gsutil#172]
A simple upload should not require direct seeks on the input.  See example below:

```
$ gsutil cp <(echo v1) gs://versiondeletedemo/foo
Copying file:///dev/fd/63 [Content-Type=application/octet-stream]...
Traceback (most recent call last):
  ...
  File "/usr/local/google/home/pstemari/gsutil/gslib/commands/cp.py", line 2274, in RunCommand
    shared_attrs)
  File "/usr/local/google/home/pstemari/gsutil/gslib/command.py", line 803, in Apply
    use_thr_exc_handler=ignore_subprocess_failures)
  File "/usr/local/google/home/pstemari/gsutil/gslib/command.py", line 908, in _ApplyThreads
    return_value = func(args)
  File "/usr/local/google/home/pstemari/gsutil/gslib/commands/cp.py", line 2144, in _CopyFunc
    self._PerformCopy(exp_src_uri, dst_uri))
  File "/usr/local/google/home/pstemari/gsutil/gslib/commands/cp.py", line 1607, in _PerformCopy
    download_headers)
  File "/usr/local/google/home/pstemari/gsutil/gslib/commands/cp.py", line 1241, in _UploadFileToObject
    self._GetFileSize(src_key.fp)))
  File "/usr/local/google/home/pstemari/gsutil/gslib/commands/cp.py", line 1036, in _PerformResumableUploadIfApplies
    res_upload_handler=res_upload_handler)
  File "/usr/local/google/home/pstemari/gsutil/third_party/boto/boto/storage_uri.py", line 671, in set_contents_from_file
    rewind=rewind, res_upload_handler=res_upload_handler)
  File "/usr/local/google/home/pstemari/gsutil/third_party/boto/boto/gs/key.py", line 515, in set_contents_from_file
    spos = fp.tell()
IOError: [Errno 29] Illegal seek
```

**Comment by thobrla** [comment]
This works now (at least for the default JSON API).
