### ISSUE TITLE
gsutil cat prints stack trace when used in pipe

### ISSUE THREAD

**Issue by pstemari** [GoogleCloudPlatform/gsutil#173]
Broken pipe when writing cat output should just exit silently.

```
$ gsutil cat gs://pub/SomeOfTheTeam.jpg | hexdump | head
0000000 d8ff e0ff 1000 464a 4649 0100 0001 0100
0000010 0100 0000 dbff 8400 0500 0403 1010 100f
0000020 1010 1010 1010 1010 1010 1010 1010 1010
0000030 1010 1010 0f10 1010 1010 1010 100f 1010
0000040 0f10 0d10 0f0d 0f15 1110 1311 1313 0d0d
0000050 1816 1216 1018 1312 0112 0505 0805 0807
0000060 090f 0f09 1417 1512 1414 1417 1415 1417
0000070 1714 1414 1414 1414 1414 1414 1414 1414
0000080 1414 1414 1414 1414 1414 1414 1414 1414
0000090 1414 1414 1414 1414 1414 c0ff 1100 0208
Traceback (most recent call last):
  File "/usr/local/google/home/pstemari/bin/gsutil", line 88, in <module>
    sys.exit(gslib.__main__.main())
  File "/usr/local/google/home/pstemari/gsutil/gslib/__main__.py", line 246, in main
    parallel_operations)
  File "/usr/local/google/home/pstemari/gsutil/gslib/__main__.py", line 336, in _RunNamedCommandAndHandleExceptions
    parallel_operations)
  File "/usr/local/google/home/pstemari/gsutil/gslib/command_runner.py", line 187, in RunNamedCommand
    return command_inst.RunCommand()
  File "/usr/local/google/home/pstemari/gsutil/gslib/commands/cat.py", line 165, in RunCommand
    key.get_file(cat_outfd, headers)
  File "/usr/local/google/home/pstemari/gsutil/third_party/boto/boto/gs/key.py", line 173, in get_file
    query_args=query_args)
  File "/usr/local/google/home/pstemari/gsutil/third_party/boto/boto/s3/key.py", line 1472, in _get_file_internal
    fp.write(bytes)
IOError: [Errno 32] Broken pipe
```

**Comment by thobrla** [comment]
The broken pipe error is gone in gsutil 4 (JSON API), not sure this is worth solving more generally.
