### ISSUE TITLE
gsutil copy -R appears to be broken for me

### ISSUE THREAD

**Issue by julianjon** [GoogleCloudPlatform/gsutil#181]
I'm using linux mint, gsutil version 3.42
```
> gsutil cp -R gs://.../templates/ ./templates
> CommandException: Destination URI must name a directory, bucket, or bucket
> mkdir templates
> gsutil cp -R gs://.../templates/ ./templates
Copying gs://.../templates/...
Traceback (most recent call last):
  File "/home/julian/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/home/julian/gsutil/gsutil.py", line 96, in RunMain
    sys.exit(gslib.__main__.main())
  File "/home/julian/gsutil/gslib/__main__.py", line 276, in main
    parallel_operations)
  File "/home/julian/gsutil/gslib/__main__.py", line 366, in _RunNamedCommandAndHandleExceptions
    parallel_operations)
  File "/home/julian/gsutil/gslib/command_runner.py", line 190, in RunNamedCommand
    return_values = command_inst.RunCommand()
  File "/home/julian/gsutil/gslib/commands/cp.py", line 2275, in RunCommand
    _CopyExceptionHandler, shared_attrs, fail_on_error=True)
  File "/home/julian/gsutil/gslib/command.py", line 975, in Apply
    arg_checker, should_return_results, fail_on_error)
  File "/home/julian/gsutil/gslib/command.py", line 1024, in _SequentialApply
    worker_thread.PerformTask(task, self)
  File "/home/julian/gsutil/gslib/command.py", line 1421, in PerformTask
    results = task.func(cls, task.args)
  File "/home/julian/gsutil/gslib/commands/cp.py", line 579, in _CopyFuncWrapper
    cls._CopyFunc(args)
  File "/home/julian/gsutil/gslib/commands/cp.py", line 2164, in _CopyFunc
    self._PerformCopy(exp_src_uri, dst_uri))
  File "/home/julian/gsutil/gslib/commands/cp.py", line 1657, in _PerformCopy
    download_headers)
  File "/home/julian/gsutil/gslib/commands/cp.py", line 1384, in _DownloadObjectToFile
    fp = open(download_file_name, 'wb')
IOError: [Errno 21] Is a directory: u'./templates/templates/'
```

**Comment by thobrla** [comment]
This has been fixed for a while in gsutil 4, sorry I never got around to closing this issue.
