### ISSUE TITLE
pkg_resources.DistributionNotFound: boto==2.29.1

### ISSUE THREAD

**Issue by obeleh** [GoogleCloudPlatform/gsutil#206]
```
gsutil cp failed.tar.gz gs://my_bucket
Traceback (most recent call last):
  File "/usr/local/bin/gsutil", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: boto==2.29.1
```

But:

```
pip freeze | grep boto
boto==2.29.1
gcs-oauth2-boto-plugin==1.5
```

Huh what?
I'm running on a Debian Wheezy GCE instance and tried the following updates:

```
sudo apt-get update
sudo apt-get upgrade
sudo pip install -U boto
sudo pip install -U gsutil
curl https://sdk.cloud.google.com | bash
```

```
Requirement already up-to-date: gsutil in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: boto==2.29.1 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: crcmod>=1.7 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: gcs-oauth2-boto-plugin>=1.5 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: google-api-python-client>=1.1 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: httplib2>=0.8 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: pyOpenSSL>=0.13 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: python-gflags>=2.0 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: retry-decorator>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: SocksiPy-branch==1.01 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: cryptography>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.13->gsutil)
Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.13->gsutil)
Requirement already up-to-date: cffi>=0.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
```

**Comment by sanket-rathi** [comment]
I am trying to create a local pip repo for gsutil (for air gap environment). For that I am downloading all the dependencies and gsutil using followinn commands.
# python3 -m pip download --no-binary=:all: gsutil
or 
# pip-download gsutil

This downloads all the dependencies and gsutil and I am trying to install on a different platform hence I use only source from here. 
But the problem is with the mock package. 
In gsutil mock dependency is defined as "mock==2.0.0" so only version 2.0.0 is downloaded and get installed.
But version 2.0.0 has issue 
https://github.com/testing-cabal/mock/issues/467
I need the latest version but if I put latest version in the repo that doesn't work if I use pip command to install gsutil.
I think gsutil should relax the dependency to "mock>=2.0.0" 
I am not finding a solution for this.
