### ISSUE TITLE
Failure: initializer for ctype 'char *'

### ISSUE THREAD

**Issue by lloydoliver** [GoogleCloudPlatform/gsutil#215]
This morning our backup server stopped sending files to GCS, gsutil commands resulted in 

```
Failure: initializer for ctype 'char *' must be a str or list or tuple, not unicode.
```

removed gsutil and reinstalled clean via pip and now resulting in;

```
root@backup-001:~# gsutil
Traceback (most recent call last):
  File "/usr/local/bin/gsutil", line 9, in <module>
    load_entry_point('gsutil==4.4', 'console_scripts', 'gsutil')()
  File "/usr/local/share/google/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 176, in main
    command_runner = CommandRunner()
  File "/usr/local/share/google/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 107, in __init__
    self.command_map = self._LoadCommandMap()
  File "/usr/local/share/google/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 113, in _LoadCommandMap
    __import__('gslib.commands.%s' % module_name)
  File "/usr/local/share/google/google-cloud-sdk/platform/gsutil/gslib/commands/test.py", line 39, in <module>
    from gslib.tests.util import GetTestNames
  File "/usr/local/share/google/google-cloud-sdk/platform/gsutil/gslib/tests/util.py", line 136, in <module>
    import mock_storage_service
ImportError: No module named mock_storage_service
```

during install;

```
Downloading/unpacking gsutil
  Downloading gsutil-4.4.tar.gz (492Kb): 492Kb downloaded
  Running setup.py egg_info for package gsutil

    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'gslib/commands/update.py'
    warning: no files found matching '*' under directory 'scripts'
Requirement already up-to-date: boto==2.30.0 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: crcmod>=1.7 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: gcs-oauth2-boto-plugin>=1.7 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: google-api-python-client>=1.1 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: httplib2>=0.8 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: pyOpenSSL>=0.13 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: python-gflags>=2.0 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: retry-decorator>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: SocksiPy-branch==1.01 in /usr/local/lib/python2.7/dist-packages (from gsutil)
Requirement already up-to-date: cryptography>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.13->gsutil)
Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL>=0.13->gsutil)
Requirement already up-to-date: cffi>=0.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
Installing collected packages: gsutil
  Running setup.py install for gsutil

    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'gslib/commands/update.py'
    warning: no files found matching '*' under directory 'scripts'
    Installing gsutil script to /usr/local/bin
Successfully installed gsutil
Cleaning up...
```

```
root@backup-001:~# pip freeze | egrep (google|gsutil|boto)
boto==2.30.0
gcs-oauth2-boto-plugin==1.7
google-api-python-client==1.2
gsutil==4.4
```

```
root@backup-001:~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
```

Normally our systems are managed by SaltStack and nothing has been committed to the salt repo since gsutil was last working, letting salt redploy the packages results in the same errors.

**Comment by houglum** [comment]
For the sake of discoverability:

The bug here can be traced back to years-old versions of the `pyopenssl` package:  https://github.com/pyca/pyopenssl/issues/15.  I encountered this yesterday when testing on Google Compute Engine VMs running our Debian 8 images -- it turns out that installing the `python-openssl` package will, by default, result in having a *really* old version (0.14.0).  

This can be fixed either by installing from the Debian 8 backports repository (adding `-t jessie-backports` to the `apt-get install` command), or by using `pip` to install a more current version of the `pyopenssl` package... note that this requires a few <foo>-dev packages -- I had to run these commands when taking the latter approach:

    $ sudo apt-get install python-pip
    $ sudo apt-get python-devel libssl-dev libffi-dev
    $ sudo pip install --upgrade cffi cryptography pyopenssl
