### ISSUE TITLE
gsutil rsync pegs CPU at 100% if it encounters an S3 Glacier object

### ISSUE THREAD

**Issue by STRML** [GoogleCloudPlatform/gsutil#242]
I run a synchronization job at intervals from an S3 bucket to a gcloud bucket.

That S3 bucket has a policy that moves items to Glacier at intervals.

I don't expect gsutil rsync to be able to rsync glacier files - while it would be nice, it's quite a process - but it should be able to skip over them properly.

Instead, I see this message in the logs, and the process stops working but maintains 100% cpu usage, making the system unresponsive:

```
Copying s3://path/file.ext [Content-Type=application/octet-stream]...
Exception in thread Thread-13:file.ext: 0 B/54.36 KiB
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gslib/daisy_chain_wrapper.py", line 148, in PerformDownload
    provider=self.src_url.scheme)
  File "/usr/local/lib/python2.7/dist-packages/gslib/cloud_api_delegator.py", line 219, in GetObjectMedia
    serialization_data=serialization_data, digesters=digesters)
  File "/usr/local/lib/python2.7/dist-packages/gslib/boto_translation.py", line 441, in GetObjectMedia
    generation=generation)
  File "/usr/local/lib/python2.7/dist-packages/gslib/boto_translation.py", line 1364, in _TranslateExceptionAndRaise
    raise translated_exception
AccessDeniedException: AccessDeniedException: 403 InvalidObjectState
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidObjectState</Code><Message>The operation is not valid for the object's storage class</Message><RequestId>{reqID}</RequestId><HostId>{hostID}</HostId></Error>
```

**Comment by thobrla** [comment]
Fix for the process hang bug is in the works.

Special-casing glacier-class objects will be more complex, but hopefully the fix for this can make it into 4.8.

**Comment by thobrla** [comment]
Hang fixed with https://github.com/GoogleCloudPlatform/gsutil/commit/32b1b55926fe5518295e340f18fcf0a4d7d59d40 and will be included in 4.8.

**Comment by STRML** [comment]
In 4.8 the CPU is no longer pegged at 100%, but I instead just get an infinite hang.

If I terminate, the trace is:

```
user@backup-synchronizer ~> gsutil -m rsync -n -r s3://company-backups/prod/project gs://company-backups/prod/project
Building synchronization state...
Skipping cloud sub-directory placeholder object (s3://company-backups/prod/project/) because such objects aren't needed in (and would interfere with) directories in the local file system
^CCaught ^C - exiting
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 72, in <module>
    main()
  File "/usr/local/bin/../share/google/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 55, in main
    'platform/gsutil', 'gsutil', *args)
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 45, in ExecutePythonTool
    execution_utils.ArgsForPythonTool(_FullPath(tool_dir, exec_name), *args))
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 86, in _ExecuteTool
    execution_utils.Exec(args + sys.argv[1:], env=_GetToolEnv())
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/util/execution_utils.py", line 146, in Exec
    ret_val = p.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1301, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
fish: Job 1, “gsutil -m rsync -n -r s3://company-backups/prod/project gs://company-backups/prod/project” terminated by signal SIGINT (Quit request from job control (^C))
```

**Comment by thobrla** [comment]
gsutil 4.13 will support a -U option for cp and rsync that will allow you to skip glacier files: https://github.com/GoogleCloudPlatform/gsutil/commit/bc38ae2ad455956b00d247b9aec87963f96fa2a8

Please reopen if you encounter any issues.
