### ISSUE TITLE
Installation with pip: cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil => [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by nether-cat** [GoogleCloudPlatform/gsutil#259]
I ran into this issue and I am not sure what the cause might be. Googling for this problem makes me feel, that many others run into similar errors trying to install python packages within the last few weeks.

My system is FreeBSD 10.1 with Python 2.7.9

Is there a solution for this?

``` bash
~ # sudo pip install gsutil
Collecting gsutil
  Using cached gsutil-4.11.tar.gz
Collecting boto==2.30.0 (from gsutil)
  Using cached boto-2.30.0-py2-none-any.whl
Collecting crcmod>=1.7 (from gsutil)
  Using cached crcmod-1.7.tar.gz
Collecting gcs-oauth2-boto-plugin>=1.8 (from gsutil)
  Using cached gcs-oauth2-boto-plugin-1.8.tar.gz
Collecting httplib2>=0.8 (from gsutil)
  Using cached httplib2-0.9.tar.gz
Collecting oauth2client>=1.4.4 (from gsutil)
  Using cached oauth2client-1.4.6.tar.gz
Collecting pyOpenSSL>=0.13 (from gsutil)
  Using cached pyOpenSSL-0.14.tar.gz
Collecting python-gflags>=2.0 (from gsutil)
  Using cached python-gflags-2.0.tar.gz
Collecting retry-decorator>=1.0.0 (from gsutil)
  Using cached retry_decorator-1.0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.8.0 in /usr/local/lib/python2.7/site-packages (from gsutil)
Collecting SocksiPy-branch==1.01 (from gsutil)
  Using cached SocksiPy-branch-1.01.tar.gz
Collecting google-api-python-client>=1.1 (from gcs-oauth2-boto-plugin>=1.8->gsutil)
  Using cached google-api-python-client-1.4.0.tar.gz
Collecting pyasn1==0.1.7 (from oauth2client>=1.4.4->gsutil)
  Using cached pyasn1-0.1.7.tar.gz
Collecting pyasn1-modules==0.0.5 (from oauth2client>=1.4.4->gsutil)
  Using cached pyasn1-modules-0.0.5.tar.gz
Collecting rsa==3.1.4 (from oauth2client>=1.4.4->gsutil)
  Using cached rsa-3.1.4.tar.gz
Collecting cryptography>=0.2.1 (from pyOpenSSL>=0.13->gsutil)
  Using cached cryptography-0.8.tar.gz
Requirement already satisfied (use --upgrade to upgrade): uritemplate>=0.6 in /usr/local/lib/python2.7/site-packages (from google-api-python-client>=1.1->gcs-oauth2-boto-plugin>=1.8->gsutil)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/site-packages (from cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
Requirement already satisfied (use --upgrade to upgrade): cffi>=0.8 in /usr/local/lib/python2.7/site-packages (from cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
Requirement already satisfied (use --upgrade to upgrade): simplejson>=2.5.0 in /usr/local/lib/python2.7/site-packages (from uritemplate>=0.6->google-api-python-client>=1.1->gcs-oauth2-boto-plugin>=1.8->gsutil)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL>=0.13->gsutil)
Installing collected packages: cryptography, rsa, pyasn1-modules, pyasn1, google-api-python-client, SocksiPy-branch, retry-decorator, python-gflags, pyOpenSSL, oauth2client, httplib2, gcs-oauth2-boto-plugin, crcmod, boto, gsutil
  Running setup.py install for cryptography
    Download error on https://pypi.python.org/simple/pyasn1/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
    Couldn't find index page for 'pyasn1' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
    No local packages or download links found for pyasn1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VK6v8u/cryptography/setup.py", line 342, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 886, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 607, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pyasn1')
    Complete output from command /usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-VK6v8u/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" build_ext -I/usr/local/include install --record /tmp/pip-DfKzTc-record/install-record.txt --single-version-externally-managed --compile:
    Download error on https://pypi.python.org/simple/pyasn1/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!

    Couldn't find index page for 'pyasn1' (maybe misspelled?)

    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!

    No local packages or download links found for pyasn1

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-VK6v8u/cryptography/setup.py", line 342, in <module>

        **keywords_with_side_effects(sys.argv)

      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup

        _setup_distribution = dist = klass(attrs)

      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 262, in __init__

        self.fetch_build_eggs(attrs['setup_requires'])

      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs

        replace_conflicting=True,

      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve

        dist = best[req.key] = env.best_match(req, ws, installer)

      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in best_match

        return self.obtain(req, installer)

      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 886, in obtain

        return installer(requirement)

      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in fetch_build_egg

        return cmd.easy_install(req)

      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 607, in easy_install

        raise DistutilsError(msg)

    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pyasn1')

    ----------------------------------------
```

This is my pip freeze output:

``` bash
~ # pip freeze
cffi==0.9.2
enum34==1.0.4
gdbm==0.0.0
Glances==2.1
powerline-status==2.1
psutil==2.2.1
pycparser==2.10
python-dateutil==2.3
python-magic==0.4.6
pyzor==0.5.0
s3cmd==1.5.2
simplejson==3.6.5
six==1.8.0
uritemplate==0.6
```

**Comment by Capstan** [comment]
Seems like you may not have python.org's root SSL certificate in your root store? Python 2.7.9 enabled [cert validation by default](https://www.python.org/dev/peps/pep-0476/). You can opt out, e.g., through [--allow-unverified cryptography](https://pip.pypa.io/en/latest/reference/pip_wheel.html#cmdoption--allow-unverified), but I suggest rather digging in to where your Python is pulling root certificates and seeing if there's an update to include the root certificate for the cert published for https://pypi.python.org/

**Comment by houglum** [comment]
Found this while searching for SSL issues; closing, as this is almost 4 years old at this point.
