### ISSUE TITLE
gsutil cp download fails "Failure: zero length field name in format." (Centos6/Py2.6)

### ISSUE THREAD

**Issue by LawrenceK** [GoogleCloudPlatform/gsutil#296]
Running on Centos 6 - Python 2.6

Work Around:
 Disable sliced object download

In ~/.boto
[GSUtil]
sliced_object_download_threshold = 0

Stack Trace
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/opt/gsutil/gslib/__main__.py", line 537, in _RunNamedCommandAndHandleExceptions
        parallel_operations)
      File "/opt/gsutil/gslib/command_runner.py", line 275, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/opt/gsutil/gslib/commands/cp.py", line 926, in RunCommand
        fail_on_error=(not self.continue_on_error))
      File "/opt/gsutil/gslib/command.py", line 1172, in Apply
        arg_checker, should_return_results, fail_on_error)
      File "/opt/gsutil/gslib/command.py", line 1243, in _SequentialApply
        worker_thread.PerformTask(task, self)
      File "/opt/gsutil/gslib/command.py", line 1707, in PerformTask
        results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
      File "/opt/gsutil/gslib/commands/cp.py", line 665, in _CopyFuncWrapper
        cls.CopyFunc(args, thread_state=thread_state)
      File "/opt/gsutil/gslib/commands/cp.py", line 817, in CopyFunc
        gzip_exts=self.gzip_exts))
      File "/opt/gsutil/gslib/copy_helper.py", line 2811, in PerformCopy
        allow_splitting=allow_splitting)
      File "/opt/gsutil/gslib/copy_helper.py", line 2308, in _DownloadObjectToFile
        copy_exception_handler, api_selector))
      File "/opt/gsutil/gslib/copy_helper.py", line 2044, in _DoSlicedDownload
        component_lengths[i])
      File "/opt/gsutil/gslib/hashing_helper.py", line 114, in ConcatCrc32c
        return _ExtendByZeros(crc_a, 8 * num_bytes_in_b) ^ crc_b
      File "/opt/gsutil/gslib/hashing_helper.py", line 152, in _ExtendByZeros
        crc = _ReverseBits32(crc)
      File "/opt/gsutil/gslib/hashing_helper.py", line 151, in _ReverseBits32
        return int('{:032b}'.format(crc, width=32)[::-1], 2)
    ValueError: zero length field name in format

**Comment by thobrla** [comment]
Thanks very much for the report - this will be fixed in gsutil 4.15.
