### ISSUE TITLE
Connection reset by peer when attempting to rsync between gs:// and s3://

### ISSUE THREAD

**Issue by bshi** [GoogleCloudPlatform/gsutil#311]
```
$ gsutil --version
gsutil version: 4.15
```

This is a fresh version of gsutil installed via the latest version of pip.  I have confirmed that I can run both ls and cp commands successfully using gs:// and s3://.  rsync, though, seems to barf.

```
$ gsutil rsync -r gs://acme-bucket/artifacts/service-artifact s3://acme-bucket-mirror/artifacts/service-artifact
Building synchronization state...
Starting synchronization
Copying gs://acme-bucket/artifacts/service-artifact/3/original-service-1.0-SNAPSHOT.jar [Content-Type=application/java-archive]...
Traceback (most recent call last):
  File "/home/vagrant/bin/gsutil", line 11, in <module>
    sys.exit(main())
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/__main__.py", line 359, in main
    parallel_operations=parallel_operations)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/__main__.py", line 537, in _RunNamedCommandAndHandleExceptions
    parallel_operations)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/command_runner.py", line 277, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/commands/rsync.py", line 1007, in RunCommand
    fail_on_error=True)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/command.py", line 1172, in Apply
    arg_checker, should_return_results, fail_on_error)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/command.py", line 1243, in _SequentialApply
    worker_thread.PerformTask(task, self)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/command.py", line 1707, in PerformTask
    results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/commands/rsync.py", line 902, in _RsyncFunc
    headers=cls.headers)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/copy_helper.py", line 2819, in PerformCopy
    preconditions, gsutil_api, logger)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/copy_helper.py", line 2584, in _CopyObjToObjDaisyChainMode
    tracker_callback=_DummyTrackerCallback)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/cloud_api_delegator.py", line 251, in UploadObjectResumable
    tracker_callback=tracker_callback, progress_callback=progress_callback)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/boto_translation.py", line 824, in UploadObjectResumable
    preconditions=preconditions, fields=fields, size=size)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/boto_translation.py", line 883, in UploadObject
    headers=headers)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/gslib/boto_translation.py", line 703, in _PerformSimpleUpload
    cb=progress_callback, headers=headers)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/boto/storage_uri.py", line 680, in set_contents_from_file
    rewind=rewind)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/path/to/ve/gsutil/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.error: [Errno 104] Connection reset by peer
```

**Comment by mfschwartz** [comment]
Hi - are you running behind a proxy by any chance? I'm wondering if the proxy is resetting the connection.

When you say you ran gsutil cp successfully, was it just one or two files, or did you try gsutil cp -r on this same source/destination?

**Comment by bshi** [comment]
Hi @mfschwartz - not running behind a proxy.  Regarding the plain gsutil cp, it was just one trivially small file.  After a bit more investigating, it seems to be S3 in particular:

I was able to run

```
gsutil rsync -r gs://acme-bucket/artifacts/service-artifact /tmp/foo
```

successfully.  A subsequent call to

```
gsutil rsync -rn /tmp/foo s3://acme-bucket-mirror/artifacts/service-artifact
```

correctly identified the appropriate new files to be copied but

```
gsutil rsync -r /tmp/foo s3://acme-bucket-mirror/artifacts/service-artifact
```

triggered another connection reset

**Comment by mfschwartz** [comment]
Hi,

This sounds like it might be the same as https://github.com/boto/boto/issues/2207
What region is your S3 bucket in?
You might try changing to using this naming: s3://s3-<region>.amazonaws.com/acme-bucket-mirror/

**Comment by bshi** [comment]
@mfschwartz sorry for the delay.  It looks like indeed that is the issue though I haven't had much luck in a brief attempt to working around it.

**Comment by mfschwartz** [comment]
@bshi - ok, if you find something different is needed please tell me so we can update our recommendations - I added code so gsutil catches this exception and offers advice when this happens, so anything you can suggest to make it more clear would be appreciated.

**Comment by afterlastangel** [comment]
I found this is the problem of the boto library itself
edit this file for workaround
/usr/lib/google-cloud-sdk/platform/gsutil/third_party/boto/boto/storage_uri.py:113
`            elif self.scheme == 's3':
                from boto.s3 import connect_to_region
                self.connection = connect_to_region('ap-southeast-1',
                                               aws_access_key_id=access_key_id,
                                               aws_secret_access_key=secret_access_key)
                self.provider_pool[self.scheme] = self.connection
            elif self.scheme == 'gs':`
