### ISSUE TITLE
NameError: name 'StandardError' is not defined

### ISSUE THREAD

**Issue by ayush--s** [GoogleCloudPlatform/gsutil#317]
```bash
ayush:/code $ gsutil ls gs://uspto-pair/applications/0800401*
Traceback (most recent call last):
  File "/usr/local/bin/gsutil", line 9, in <module>
    load_entry_point('gsutil==4.16', 'console_scripts', 'gsutil')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/gslib/__init__.py", line 31, in <module>
    import gslib.exception
  File "/usr/local/lib/python3.4/dist-packages/gslib/exception.py", line 30, in <module>
    class AbortException(StandardError):
NameError: name 'StandardError' is not defined
```

**Comment by thobrla** [comment]
It looks like you're using Python 3.4.  gsutil only supports Python 2.6 and 2.7.  https://github.com/GoogleCloudPlatform/gsutil/issues/29 tracks adding Python 3 support.
