### ISSUE TITLE
rsync: can't start new thread

### ISSUE THREAD

**Issue by bluehayes** [GoogleCloudPlatform/gsutil#318]
Hi,

I've been fine running gsutil on one CentOS 7 system. However on a new system, running CloudLinux 7, I'm now running into errors with rsync operations. Other operations such as ls/cp/rm all work fine, although the `-m` option is also giving me (different) errors.

Does anybody know what could be causing the below issues or is it a gsutil bug?

```
root@system [~]# gsutil -m rsync -dr /some/dir gs://some-bucket/some-dir
Building synchronization state...
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/gsutil/gslib/command.py", line 1448, in _ApplyThreads
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/gsutil/gslib/command.py", line 1448, in _ApplyThreads
    gsutil_api_map=self.gsutil_api_map, debug=self.debug)
  File "/root/gsutil/gslib/command.py", line 1656, in __init__
    worker_thread.start()
  File "/usr/lib64/python2.7/threading.py", line 746, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
    gsutil_api_map=self.gsutil_api_map, debug=self.debug)
  File "/root/gsutil/gslib/command.py", line 1656, in __init__
    worker_thread.start()
  File "/usr/lib64/python2.7/threading.py", line 746, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Process SyncManager-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/lib64/python2.7/threading.py", line 746, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/gsutil/gslib/command.py", line 1448, in _ApplyThreads
    gsutil_api_map=self.gsutil_api_map, debug=self.debug)
  File "/root/gsutil/gslib/command.py", line 1656, in __init__
    worker_thread.start()
  File "/usr/lib64/python2.7/threading.py", line 746, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

Thanks

**Comment by thobrla** [comment]
This is below the level of what gsutil can control, but if you're running out of process/thread resources on your system you can reduce the parallel_process_count and parallel_thread_count values in your .boto config file.

**Comment by bluehayes** [comment]
Thanks, I will look into that - perhaps it's related to the system running CloudLinux. I had switched to root user though, plus the system doesn't have much going on (it's newly deployed although cPanel and related services are installed). I'll update if I have any further info for anybody Googling similar problems.

**Comment by bluehayes** [comment]
I have discovered that this issue was related to CloudLinux LVE limits. The limits should not be applied after switching user into root (as far as I know) but they are being applied, so I've opened a ticket with them to discuss the matter further.e

**Comment by thobrla** [comment]
Thanks for looking into it.
