### ISSUE TITLE
oauth2client version conflict

### ISSUE THREAD

**Issue by yodax** [GoogleCloudPlatform/gsutil#333]
This seems related to https://github.com/GoogleCloudPlatform/gsutil/issues/330

After the latest updates I get a new error: 

```
gsutil
Traceback (most recent call last):
  File "/usr/local/bin/gsutil", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (oauth2client 1.5.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('oauth2client<3,>=2.0.0'), set(['google-api-python-client']))
```
Updating the oauth2client doesn't work. That will give:

The 'oauth2client==1.5.2' distribution was not found and is required by gsutil

**Comment by Lastpixl** [comment]
Hi,
I'm getting the same problem.
gsutil 4.17 requires gcs-oauth2-boto-plugin >= 1.9
gsutil 4.17 requires oauth2client==1.5.2
gcs-oauth2-boto-plugin 1.9 requires google-api-python-client >= 1.1
google-api-python-client 1.5.0 Requires-Dist oauth2client (>=2.0.0,<3)

=> conflict on oauth2client required versions.

**Comment by peet86** [comment]
Same here.. update doesn't work.. :(

**Comment by errordeveloper** [comment]
I have noticed the same issue, which I fixed by replacing `pip install gsutil` with `pip install pyopenssl && curl --silent --location https://storage.googleapis.com/pub/gsutil.tar.gz | tar xz -C $HOME`. Seems like installation via pip is not officially supported...

**Comment by thobrla** [comment]
Thanks for the reports, all.  I'm not sure how this made it through our pip install tests, but I'll work on getting gcs-oauth2-boto-plugin amended and a new release pushed out.  This may take a couple days, though.

**Comment by thobrla** [comment]
We'll increment the next release of gsutil as well, the gsutil 4.17 install should pick up gcs-oauth2-boto-plugin 1.10, which fixes this issue.
