### ISSUE TITLE
gsutil - Traceback error

### ISSUE THREAD

**Issue by hodkamail** [GoogleCloudPlatform/gsutil#338]
I have just installed gsutil on my Debian 8.3 x64 server using the pip installer, however when I run gsutil, I get the following...

```
root@London:/home/andy# gsutil
Traceback (most recent call last):
  File "/usr/local/bin/gsutil", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography>=0.7
```

I have already searched on Google for this error and followed a few other solutions, but none of them helped fix this.

Any ideas?

**Comment by houglum** [comment]
I'm assuming there was a Python package dependency conflict (maybe another package required a newer version of one of the libraries we depend on, etc.) on your local system causing this.  If you're still encountering this, I'd recommend pip-installing gsutil in a virtual environment to avoid such conflicts.
