### ISSUE TITLE
gsutil cp "Illegal seek" with xml api + input from redirect fd

### ISSUE THREAD

**Issue by euank** [GoogleCloudPlatform/gsutil#351]
When using the xml api, uploading an fd from a redirect fd (`<(echo ....)`) fails.

```
$ gsutil version
gsutil version: 4.18
```

Working command:

```
$ gsutil -o "GSUtil:prefer_api=json" -q cp <(echo "foo") gs://some-bucket/some-object
# success
```

Breaking command:

```
$ gsutil -o "GSUtil:prefer_api=xml" -q cp <(echo "foo") gs://some-bucket/some-object
Traceback (most recent call last):
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gsutil.py", line 106, in RunMain
    sys.exit(gslib.__main__.main())
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 373, in main
    perf_trace_token=perf_trace_token)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 551, in _RunNamedCommandAndHandleExceptions
    parallel_operations, perf_trace_token=perf_trace_token)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 280, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 957, in RunCommand
    fail_on_error=(not self.continue_on_error))
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1172, in Apply
    arg_checker, should_return_results, fail_on_error)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1243, in _SequentialApply
    worker_thread.PerformTask(task, self)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1705, in PerformTask
    results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 696, in _CopyFuncWrapper
    cls.CopyFunc(args, thread_state=thread_state)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 848, in CopyFunc
    gzip_exts=self.gzip_exts))
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 2921, in PerformCopy
    allow_splitting=allow_splitting)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 1657, in _UploadFileToObject
    dst_obj_metadata, preconditions, gsutil_api, logger)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 1389, in _UploadFileToObjectNonResumable
    fields=UPLOAD_RETURN_FIELDS)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 260, in UploadObject
    encryption_tuple=encryption_tuple, fields=fields)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 887, in UploadObject
    headers=headers)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 704, in _PerformSimpleUpload
    cb=progress_callback, headers=headers)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/third_party/boto/boto/storage_uri.py", line 671, in set_contents_from_file
    rewind=rewind, res_upload_handler=res_upload_handler)
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/third_party/boto/boto/gs/key.py", line 521, in set_contents_from_file
    spos = fp.tell()
  File "/home/jenkins/cloudsdk/google-cloud-sdk/platform/gsutil/gslib/hashing_helper.py", line 415, in tell
    return self._orig_fp.tell()
IOError: [Errno 29] Illegal seek
```

**Comment by thobrla** [comment]
This is a combination of two issues:
1. The boto implementation performs a seek to the beginning of the file for the purposes of end-to-end integrity checking.
2. gsutil doesn't have any special detection logic for redirect file descriptors, and it is trying to treat it like a (seekable) file.

It's unlikely 1. will be fixed, and it's also unlikely that we'll add special casing to detect 2.

If you want to copy a non-seekable stream using the XML API, can you use the `-` argument like so?

`echo foo | gsutil -o "GSUtil:prefer_api=xml" cp - gs://some-bucket/some-object`

Note that the bucket creation bug (where the service returns 503) will be fixed in the service sometime in the near future, at which point you can avoid using prefer_api=xml and hitting this case

**Comment by euank** [comment]
Yes, I can work around it by changing each instance of the pattern as you suggest, but when the code in question is in other's scripts, it's inconvenient to do so and just because there's a workaround like that doesn't mean that this isn't a real issue.

If I were to get the boto issue in question fixed upstream, would you be willing to pull it in? If so, I'd like to give that shot.

**Comment by thobrla** [comment]
I'm not convinced the fix is simple or limited to boto.  To do this safely, we would need to evaluate each source file argument to determine whether it is a non-seekable file descriptor.  That the boto implementation seeks by default makes the issue worse, but even using the JSON API, a sufficiently large descriptor would be problematic.  If the connection breaks, we may attempt to seek backwards in the "file" to resume the upload, only to find that the seek can't be performed.

With that in mind, I think the best solution actually is to change instances of the pattern to use the streaming argument that I mentioned.  This indicates to gsutil that the input is indeed non-seekable.

I'm definitely amenable to pulling in a boto fix to improve the seek behavior if one is made, but you'd also need to convince the boto authors to put out a boto release.  I'm confident the JSON API service bug will be fixed much sooner than that.

Finally, while I agree it's a real issue, is it one that has been present for over 2 years, with this being the first time it has come up.  So I'm doubtful there is a large corpus of existing user scripts that have this problem.

**Comment by euank** [comment]
I think you're probably right that it's okay to leave this be since, as you say, it's a behavior that's existed for years and years now.

I'll close this issue since I don't expect to do anything here, and it doesn't sound like it impacts anyone else / is obviously something worth fixing.

I appreciate the detailed response (several years ago)!
