### ISSUE TITLE
Add support for S3 user-specific directories

### ISSUE THREAD

**Issue by julianvmodesto** [GoogleCloudPlatform/gsutil#366]
I'm receiving Access Denied with `ls` and `rsync` for S3 user-specific directories :( it would be great if gsutil could support S3 user-specific directories for simple migration to GS

**Comment by thobrla** [comment]
Do you have any more detail on what's necessary to support this?  Is the issue that the [boto](https://github.com/boto/boto) library doesn't support a method of authenticating as a user?  Or that you need to configure IAM on this directory in a certain way?

**Comment by julianvmodesto** [comment]
Possibly boto... I have an IAM user with permission to access to a specific S3 folder prefix, but not to the root-level bucket. I specified the AWS access and secret keys in boto, but I can't rsync the folder with gsutil.

**Comment by thobrla** [comment]
I'm not an expert on S3 IAM model, but `ls` and `rsync` require list permission.  Does the user have list permission on that folder?

**Comment by julianvmodesto** [comment]
Yes, the user does have access for listing and getting objects in that folder

**Comment by thobrla** [comment]
Using `gsutil -DD ls`, can you confirm that the request that is being denied is trying to list that folder?  Do you have an example of a request authenticated as this user that can list it successfully so that we can compare them?

**Comment by julianvmodesto** [comment]
Sorry, turns out `ls` is working, but `rsync` is failing, as well as `cp`. I guess it's failing at the actual GetObject request. I tried similar `ls` and `cp` commands with aws cli, and this works fine.

    ❯❯❯ gsutil rsync -r -d s3://bucket/folder gs://bucket/folder
    Building synchronization state...
    Starting synchronization
    Copying s3://bucket/folder/2016-06-17/part-r-00000.gz [Content-Type=binary/octet-stream]...
    Exception in thread Thread-27:r-data/2016-06-17/part-r-00000.gz: 0 B/65.31 MiB
    Traceback (most recent call last):
      File "/Users/jvm/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/Users/jvm/anaconda/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/daisy_chain_wrapper.py", line 197, in    PerformDownload
        decryption_tuple=self.decryption_tuple)
      File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 252, in    GetObjectMedia
        decryption_tuple=decryption_tuple)
      File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 493, in GetObjectMedia
        generation=generation)
      File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 1430, in  _TranslateExceptionAndRaise
        raise translated_exception
    AccessDeniedException: AccessDeniedException: 403 AccessDenied
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>D610380A5474D357</RequestId><    HostId>7UpYZ1CsFdbte+3kDYKIECTePPBUNJE1RJ0sFhLTJJmI7GXkVBxm0jsMQPg9WOz2TWeoWBdpkvI=</HostId></Error>
    
    AccessDeniedException: 403 AccessDenied
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>D610380A5474D357</RequestId><HostId>7UpYZ1CsFdbte+3kDYKIECTePPBUNJE1RJ0sFhLTJJmI7GXkVBxm0jsMQPg9WOz2TWeoWBdpkvI=</HostId></Error>

Should I send over logs from `gsutil -DD rsync`?

**Comment by thobrla** [comment]
If it's get-object that is failing, can you confirm it fails when copying that file locally?  That would produce a simpler trace.  Also, it would be useful to compare/contrast the failing get request between gsutil/s3cmd

**Comment by julianvmodesto** [comment]
Sure, below is a failing `gsutil cp` and successful `s3cmd get`

    ❯❯❯ gsutil -DD cp s3://bucket/folder/2016-06-01/part-r-00000.gz .
    gsutil version: 4.19
    checksum: 67da5fbdef140f1663fbb11e96bb9f90 (OK)
    boto version: 2.39.0
    python version: 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)]
    OS: Darwin 15.5.0
    multiprocessing available: True
    using cloud sdk: True
    config path: /Users/jvm/.boto
    gsutil path: /Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gsutil
    compiled crcmod: True
    installed via package manager: False
    editable install: False
    Command being run: /Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gsutil -o     GSUtil:default_project_id=adtech-core -DD cp s3://bucket/folder/2016-06-01/part-r-00000.gz .
    config_file_list: ['/Users/jvm/.boto', '/Users/jvm/.config/gcloud/legacy_credentials/email@gmail.com/.boto']
    config: [('debug', '0'), ('working_dir', '/mnt/pyami'), ('https_validate_certificates', 'True'), ('debug', '0'),    ('working_dir', '/mnt/pyami'), ('content_language', 'en'), ('default_api_version', '2'), ('default_project_id',   'adtech-core')]
    DEBUG 0627 10:26:38.862290 provider.py] Using access key found in shared credential file.
    DEBUG 0627 10:26:38.862489 provider.py] Using secret key found in shared credential file.
    DEBUG 0627 10:26:38.863305 connection.py] path=/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:38.863407 connection.py] auth_path=/bucket/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:38.863766 connection.py] Method: HEAD
    DEBUG 0627 10:26:38.863847 connection.py] Path: /folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:38.863938 connection.py] Data:
    DEBUG 0627 10:26:38.864032 connection.py] Headers: {}
    DEBUG 0627 10:26:38.864118 connection.py] Host: bucket.s3.amazonaws.com
    DEBUG 0627 10:26:38.864209 connection.py] Port: 443
    DEBUG 0627 10:26:38.864294 connection.py] Params: {}
    DEBUG 0627 10:26:38.864451 connection.py] establishing HTTPS connection: host=bucket.s3.amazonaws.com, kwargs={'port':    443, 'timeout': 70}
    DEBUG 0627 10:26:38.864634 connection.py] Token: None
    DEBUG 0627 10:26:38.865214 auth.py] StringToSign:
    HEAD
    
    
    Mon, 27 Jun 2016 14:26:38 GMT
    /bucket/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:38.865386 auth.py] Signature:
    AWS ACCESS_KEY:SECRET
    DEBUG 0627 10:26:38.865539 connection.py] Final headers: {'Date': 'Mon, 27 Jun 2016 14:26:38 GMT', 'Content-Length':    '0', 'Authorization': u'AWS ACCESS_KEY:SECRET', 'User-Agent': 'Boto/2.39.0 Python/2.7.11 Darwin/15.5.0 gsutil/4.19 (  darwin) Cloud SDK Command Line Tool 115.0.0'}
    DEBUG 0627 10:26:39.528205 https_connection.py] wrapping ssl socket; CA certificate file=/Users/jvm/Applications/   google-cloud-sdk/platform/gsutil/third_party/boto/boto/cacerts/cacerts.txt
    DEBUG 0627 10:26:39.571849 https_connection.py] validating server certificate: hostname=bucket.s3.amazonaws.com,    certificate hosts=['*.s3.amazonaws.com', 's3.amazonaws.com']
    send: 'HEAD /folder/2016-06-01/part-r-00000.gz HTTP/1.1\r\nHost: bucket.s3.amazonaws.com\r\nAccept-Encoding:    identity\r\nDate: Mon, 27 Jun 2016 14:26:38 GMT\r\nContent-Length: 0\r\nAuthorization: AWS    ACCESS_KEY:SECRET\r\nUser-Agent: Boto/2.39.0 Python/2.7.11 Darwin/15.5.0 gsutil/4.19 (darwin) Cloud SDK Command Line   Tool 115.0.0\r\n\r\n'
    reply: 'HTTP/1.1 200 OK\r\n'
    header: x-amz-id-2: ...
    header: x-amz-request-id: ...
    header: Date: Mon, 27 Jun 2016 14:26:45 GMT
    header: x-amz-version-id: GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt
    header: Last-Modified: Thu, 02 Jun 2016 10:04:06 GMT
    header: ETag: "8123294dc33181f0ba8fe46442789f16"
    header: x-amz-server-side-encryption: AES256
    header: Accept-Ranges: bytes
    header: Content-Type: binary/octet-stream
    header: Content-Length: 548986
    header: Server: AmazonS3
    DEBUG 0627 10:26:39.784047 connection.py] Response headers: [('content-length', '548986'), ('x-amz-id-2', '...'),     ('accept-ranges', 'bytes'), ('server', 'AmazonS3'), ('last-modified', 'Thu, 02 Jun 2016 10:04:06 GMT'),     ('x-amz-request-id', '...'), ('etag', '"8123294dc33181f0ba8fe46442789f16"'), ('date', 'Mon, 27 Jun 2016 14:26:45 GMT'),     ('x-amz-version-id', 'GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt'), ('x-amz-server-side-encryption', 'AES256'), ('content-type',    'binary/octet-stream')]
    process count: 1
    thread count: 1
    DEBUG 0627 10:26:39.861904 connection.py] path=/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:39.862049 connection.py] auth_path=/bucket/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:39.862236 connection.py] Method: HEAD
    DEBUG 0627 10:26:39.862319 connection.py] Path: /folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:39.862421 connection.py] Data:
    DEBUG 0627 10:26:39.862527 connection.py] Headers: {}
    DEBUG 0627 10:26:39.862617 connection.py] Host: bucket.s3.amazonaws.com
    DEBUG 0627 10:26:39.862708 connection.py] Port: 443
    DEBUG 0627 10:26:39.862796 connection.py] Params: {}
    DEBUG 0627 10:26:39.863008 connection.py] Token: None
    DEBUG 0627 10:26:39.863138 auth.py] StringToSign:
    HEAD
    
    
    Mon, 27 Jun 2016 14:26:39 GMT
    /bucket/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:39.863292 auth.py] Signature:
    AWS ACCESS_KEY:SECRET
    DEBUG 0627 10:26:39.863419 connection.py] Final headers: {'Date': 'Mon, 27 Jun 2016 14:26:39 GMT', 'Content-Length':    '0', 'Authorization': u'AWS ACCESS_KEY:SECRET', 'User-Agent': 'Boto/2.39.0 Python/2.7.11 Darwin/15.5.0 gsutil/4.19 (  darwin) Cloud SDK Command Line Tool 115.0.0'}
    send: 'HEAD /folder/2016-06-01/part-r-00000.gz HTTP/1.1\r\nHost: bucket.s3.amazonaws.com\r\nAccept-Encoding:    identity\r\nDate: Mon, 27 Jun 2016 14:26:39 GMT\r\nContent-Length: 0\r\nAuthorization: AWS    ACCESS_KEY:SECRET\r\nUser-Agent: Boto/2.39.0 Python/2.7.11 Darwin/15.5.0 gsutil/4.19 (darwin) Cloud SDK Command Line   Tool 115.0.0\r\n\r\n'
    reply: 'HTTP/1.1 200 OK\r\n'
    header: x-amz-id-2: ...
    header: x-amz-request-id: ...
    header: Date: Mon, 27 Jun 2016 14:26:45 GMT
    header: x-amz-version-id: GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt
    header: Last-Modified: Thu, 02 Jun 2016 10:04:06 GMT
    header: ETag: "8123294dc33181f0ba8fe46442789f16"
    header: x-amz-server-side-encryption: AES256
    header: Accept-Ranges: bytes
    header: Content-Type: binary/octet-stream
    header: Content-Length: 548986
    header: Server: AmazonS3
    DEBUG 0627 10:26:39.905501 connection.py] Response headers: [('content-length', '548986'), ('x-amz-id-2', '...'),     ('accept-ranges', 'bytes'), ('server', 'AmazonS3'), ('last-modified', 'Thu, 02 Jun 2016 10:04:06 GMT'),     ('x-amz-request-id', '...'), ('etag', '"8123294dc33181f0ba8fe46442789f16"'), ('date', 'Mon, 27 Jun 2016 14:26:45 GMT'),     ('x-amz-version-id', 'GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt'), ('x-amz-server-side-encryption', 'AES256'), ('content-type',    'binary/octet-stream')]
    Copying s3://bucket/folder/2016-06-01/part-r-00000.gz...
    DEBUG 0627 10:26:39.911226 connection.py] path=/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:39.911353 connection.py] auth_path=/bucket/folder/2016-06-01/part-r-00000.gz
    DEBUG 0627 10:26:39.911476 connection.py] path=/folder/2016-06-01/    part-r-00000.gz?versionId=GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt
    DEBUG 0627 10:26:39.911602 connection.py] auth_path=/bucket/folder/2016-06-01/    part-r-00000.gz?versionId=GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt
    DEBUG 0627 10:26:39.911762 connection.py] Method: GET
    DEBUG 0627 10:26:39.911844 connection.py] Path: /folder/2016-06-01/   part-r-00000.gz?versionId=GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt
    DEBUG 0627 10:26:39.911929 connection.py] Data:
    DEBUG 0627 10:26:39.912056 connection.py] Headers: {'range': 'bytes=0-548985', 'Range': 'bytes=0-548985'}
    DEBUG 0627 10:26:39.912181 connection.py] Host: bucket.s3.amazonaws.com
    DEBUG 0627 10:26:39.912282 connection.py] Port: 443
    DEBUG 0627 10:26:39.912397 connection.py] Params: {}
    DEBUG 0627 10:26:39.912524 connection.py] establishing HTTPS connection: host=bucket.s3.amazonaws.com, kwargs={'port':    443, 'timeout': 70}
    DEBUG 0627 10:26:39.912712 connection.py] Token: None
    DEBUG 0627 10:26:39.912884 auth.py] StringToSign:
    GET
    
    
    Mon, 27 Jun 2016 14:26:39 GMT
    /bucket/folder/2016-06-01/part-r-00000.gz?versionId=GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt
    DEBUG 0627 10:26:39.913038 auth.py] Signature:
    AWS ACCESS_KEY:SECRET
    DEBUG 0627 10:26:39.913226 connection.py] Final headers: {'Content-Length': '0', 'Range': 'bytes=0-548985',     'User-Agent': 'Boto/2.39.0 Python/2.7.11 Darwin/15.5.0 gsutil/4.19 (darwin) Cloud SDK Command Line Tool 115.0.0',     'range': 'bytes=0-548985', 'Date': 'Mon, 27 Jun 2016 14:26:39 GMT', 'Authorization': u'AWS ACCESS_KEY:SECRET'}
    DEBUG 0627 10:26:39.925940 https_connection.py] wrapping ssl socket; CA certificate file=/Users/jvm/Applications/   google-cloud-sdk/platform/gsutil/third_party/boto/boto/cacerts/cacerts.txt
    DEBUG 0627 10:26:39.969790 https_connection.py] validating server certificate: hostname=bucket.s3.amazonaws.com,    certificate hosts=['*.s3.amazonaws.com', 's3.amazonaws.com']
    send: 'GET /folder/2016-06-01/part-r-00000.gz?versionId=GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt HTTP/1.1\r\nHost:    bucket.s3.amazonaws.com\r\nAccept-Encoding: identity\r\nContent-Length: 0\r\nRange: bytes=0-548985\r\nUser-Agent:   Boto/2.39.0 Python/2.7.11 Darwin/15.5.0 gsutil/4.19 (darwin) Cloud SDK Command Line Tool 115.0.0\r\nrange:     bytes=0-548985\r\nDate: Mon, 27 Jun 2016 14:26:39 GMT\r\nAuthorization: AWS ACCESS_KEY:SECRET\r\n\r\n'
    reply: 'HTTP/1.1 403 Forbidden\r\n'
    header: x-amz-request-id: ...
    header: x-amz-id-2: ...
    header: Content-Type: application/xml
    header: Transfer-Encoding: chunked
    header: Date: Mon, 27 Jun 2016 14:26:44 GMT
    header: Server: AmazonS3
    DEBUG 0627 10:26:40.175450 connection.py] Response headers: [('x-amz-id-2', '...'), ('server', 'AmazonS3'),     ('transfer-encoding', 'chunked'), ('x-amz-request-id', '...'), ('date', 'Mon, 27 Jun 2016 14:26:44 GMT'),     ('content-type', 'application/xml')]
    DEBUG: Exception stack trace:
        Traceback (most recent call last):
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 565, in     _RunNamedCommandAndHandleExceptions
            parallel_operations, perf_trace_token=perf_trace_token)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 280, in     RunNamedCommand
            return_code = command_inst.RunCommand()
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 968, in RunCommand
            fail_on_error=(not self.continue_on_error))
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1172, in Apply
            arg_checker, should_return_results, fail_on_error)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1243, in _SequentialApply
            worker_thread.PerformTask(task, self)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1705, in PerformTask
            results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 707, in _CopyFuncWrapper
            cls.CopyFunc(args, thread_state=thread_state)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 859, in CopyFunc
            gzip_exts=self.gzip_exts))
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 2904, in PerformCopy
            decryption_key=decryption_key)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 2386, in     _DownloadObjectToFile
            gsutil_api, logger, digesters, decryption_key=decryption_key))
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 2244, in     _DownloadObjectToFileResumable
            decryption_tuple=CryptoTupleFromKey(decryption_key))
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 252, in    GetObjectMedia
            decryption_tuple=decryption_tuple)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 493, in     GetObjectMedia
            generation=generation)
          File "/Users/jvm/Applications/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 1430, in    _TranslateExceptionAndRaise
            raise translated_exception
        AccessDeniedException: AccessDeniedException: 403 AccessDenied
        <?xml version="1.0" encoding="UTF-8"?>
        <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>...</RequestId><HostId>...</HostId></Error>

And the s3cmd:

    ❯❯❯ s3cmd --access_key=... --secret_key=... --debug get s3://bucket/folder/2016-06-01/part-r-00000.gz .
    DEBUG: s3cmd version 1.6.1
    DEBUG: ConfigParser: Reading file '/Users/jvm/.s3cfg'
    DEBUG: ConfigParser: access_key->AK...17_chars...A
    DEBUG: ConfigParser: access_token->
    DEBUG: ConfigParser: add_encoding_exts->
    DEBUG: ConfigParser: add_headers->
    DEBUG: ConfigParser: bucket_location->US
    DEBUG: ConfigParser: ca_certs_file->
    DEBUG: ConfigParser: cache_file->
    DEBUG: ConfigParser: check_ssl_certificate->True
    DEBUG: ConfigParser: check_ssl_hostname->True
    DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
    DEBUG: ConfigParser: default_mime_type->binary/octet-stream
    DEBUG: ConfigParser: delay_updates->False
    DEBUG: ConfigParser: delete_after->False
    DEBUG: ConfigParser: delete_after_fetch->False
    DEBUG: ConfigParser: delete_removed->False
    DEBUG: ConfigParser: dry_run->False
    DEBUG: ConfigParser: enable_multipart->True
    DEBUG: ConfigParser: encoding->UTF-8
    DEBUG: ConfigParser: encrypt->False
    DEBUG: ConfigParser: expiry_date->
    DEBUG: ConfigParser: expiry_days->
    DEBUG: ConfigParser: expiry_prefix->
    DEBUG: ConfigParser: follow_symlinks->False
    DEBUG: ConfigParser: force->False
    DEBUG: ConfigParser: get_continue->False
    DEBUG: ConfigParser: gpg_command->None
    DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(      passphrase_fd)s -o %(output_file)s %(input_file)s
    DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(      passphrase_fd)s -o %(output_file)s %(input_file)s
    DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
    DEBUG: ConfigParser: guess_mime_type->True
    DEBUG: ConfigParser: host_base->s3.amazonaws.com
    DEBUG: ConfigParser: host_bucket->%(bucket)s.s3.amazonaws.com
    DEBUG: ConfigParser: human_readable_sizes->False
    DEBUG: ConfigParser: invalidate_default_index_on_cf->False
    DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
    DEBUG: ConfigParser: invalidate_on_cf->False
    DEBUG: ConfigParser: kms_key->
    DEBUG: ConfigParser: limitrate->0
    DEBUG: ConfigParser: list_md5->False
    DEBUG: ConfigParser: log_target_prefix->
    DEBUG: ConfigParser: long_listing->False
    DEBUG: ConfigParser: max_delete->-1
    DEBUG: ConfigParser: mime_type->
    DEBUG: ConfigParser: multipart_chunk_size_mb->15
    DEBUG: ConfigParser: multipart_max_chunks->10000
    DEBUG: ConfigParser: preserve_attrs->True
    DEBUG: ConfigParser: progress_meter->True
    DEBUG: ConfigParser: proxy_host->
    DEBUG: ConfigParser: proxy_port->0
    DEBUG: ConfigParser: put_continue->False
    DEBUG: ConfigParser: recursive->False
    DEBUG: ConfigParser: recv_chunk->65536
    DEBUG: ConfigParser: reduced_redundancy->False
    DEBUG: ConfigParser: requester_pays->False
    DEBUG: ConfigParser: restore_days->1
    DEBUG: ConfigParser: secret_key->Fu...37_chars...Z
    DEBUG: ConfigParser: send_chunk->65536
    DEBUG: ConfigParser: server_side_encryption->False
    DEBUG: ConfigParser: signature_v2->False
    DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
    DEBUG: ConfigParser: skip_existing->False
    DEBUG: ConfigParser: socket_timeout->300
    DEBUG: ConfigParser: stats->False
    DEBUG: ConfigParser: stop_on_error->False
    DEBUG: ConfigParser: storage_class->
    DEBUG: ConfigParser: urlencoding_mode->normal
    DEBUG: ConfigParser: use_https->True
    DEBUG: ConfigParser: use_mime_magic->True
    DEBUG: ConfigParser: verbosity->WARNING
    DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
    DEBUG: ConfigParser: website_error->
    DEBUG: ConfigParser: website_index->index.html
    DEBUG: Updating Config.Config access_key -> ...
    DEBUG: Updating Config.Config cache_file ->
    DEBUG: Updating Config.Config follow_symlinks -> False
    DEBUG: Updating Config.Config secret_key -> ...
    DEBUG: Updating Config.Config verbosity -> 10
    DEBUG: Unicodising 'get' using UTF-8
    DEBUG: Unicodising 's3://bucket/folder/2016-06-01/part-r-00000.gz' using UTF-8
    DEBUG: Unicodising '.' using UTF-8
    DEBUG: Command: get
    DEBUG: DeUnicodising u'folder/2016-06-01/part-r-00000.gz' using UTF-8
    DEBUG: Unicodising 'part-r-00000.gz' using UTF-8
    DEBUG: Applying --exclude/--include
    DEBUG: CHECK: part-r-00000.gz
    DEBUG: PASS: u'part-r-00000.gz'
    INFO: Summary: 1 remote files to download
    DEBUG: DeUnicodising u'.' using UTF-8
    DEBUG: DeUnicodising u'.' using UTF-8
    DEBUG: DeUnicodising u'./part-r-00000.gz' using UTF-8
    DEBUG: Unicodising './part-r-00000.gz' using UTF-8
    DEBUG: DeUnicodising u'./part-r-00000.gz' using UTF-8
    DEBUG: DeUnicodising u'./part-r-00000.gz' using UTF-8
    DEBUG: String 'folder/2016-06-01/part-r-00000.gz' encoded to 'folder/2016-06-01/part-r-00000.gz'
    DEBUG: CreateRequest: resource[uri]=/folder/2016-06-01/part-r-00000.gz
    DEBUG: Using signature v4
    DEBUG: get_hostname(bucket): bucket.s3.amazonaws.com
    DEBUG: canonical_headers = host:bucket.s3.amazonaws.com
    x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    x-amz-date:20160627T144735Z
    
    DEBUG: Canonical Request:
    GET
    /folder/2016-06-01/part-r-00000.gz
    
    host:bucket.s3.amazonaws.com
    x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    x-amz-date:20160627T144735Z
    
    host;x-amz-content-sha256;x-amz-date
    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    ----------------------
    DEBUG: signature-v4 headers: {'x-amz-content-sha256':       'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': 'AWS4-HMAC-SHA256      Credential=.../20160627/US/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=196eed8d449eb28d1     75e74b7f342e7b9352fcf4fc9a7512a2708920c5299da28', 'x-amz-date': '20160627T144735Z'}
    DEBUG: Unicodising './part-r-00000.gz' using UTF-8
    download: 's3://bucket/folder/2016-06-01/part-r-00000.gz' -> './part-r-00000.gz'  [1 of 1]
    DEBUG: get_hostname(bucket): bucket.s3.amazonaws.com
    DEBUG: ConnMan.get(): creating new connection: https://bucket.s3.amazonaws.com
    DEBUG: Using ca_certs_file None
    DEBUG: Recognized AWS S3 host, disabling initial SSL hostname check
    DEBUG: httplib.HTTPSConnection() has only context
    DEBUG: non-proxied HTTPSConnection(bucket.s3.amazonaws.com)
    DEBUG: format_uri(): /folder/2016-06-01/part-r-00000.gz
    DEBUG: Response: {'status': 400, 'headers': {'x-amz-id-2':      'UAHEBwy0r+RtjMMv4OitQTGFshye21YxQPaE4lv0IViGIFZlhbL0dRJgYyYNUDP8X4ialQC+3Ys=', 'server': 'AmazonS3',     'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': '8CFDB40140F70FD0', 'date': 'Mon, 27 Jun 2016      14:47:39 GMT', 'content-type': 'application/xml'}, 'reason': 'Bad Request'}
    DEBUG: Falling back to signature v2
    DEBUG: Using signature v2
    DEBUG: SignHeaders:       'GET\n\n\n\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:Mon, 27       Jun 2016 14:47:35 +0000\n/bucket/folder/2016-06-01/part-r-00000.gz'
    DEBUG: Unicodising './part-r-00000.gz' using UTF-8
    download: 's3://bucket/folder/2016-06-01/part-r-00000.gz' -> './part-r-00000.gz'  [1 of 1]
    DEBUG: get_hostname(bucket): bucket.s3.amazonaws.com
    DEBUG: ConnMan.get(): creating new connection: https://bucket.s3.amazonaws.com
    DEBUG: Recognized AWS S3 host, disabling initial SSL hostname check
    DEBUG: httplib.HTTPSConnection() has only context
    DEBUG: non-proxied HTTPSConnection(bucket.s3.amazonaws.com)
    DEBUG: format_uri(): /folder/2016-06-01/part-r-00000.gz
    DEBUG: Response: {'status': 200, 'headers': {'content-length': '548986', 'x-amz-id-2': '...', 'accept-ranges': 'bytes',       'server': 'AmazonS3', 'last-modified': 'Thu, 02 Jun 2016 10:04:06 GMT', 'x-amz-request-id': '...', 'etag':      '"8123294dc33181f0ba8fe46442789f16"', 'date': 'Mon, 27 Jun 2016 14:47:41 GMT', 'x-amz-version-id':      'GrfYZ3G9dbyPOixR5AR2niCM4MSoRwkt', 'x-amz-server-side-encryption': 'AES256', 'content-type': 'binary/octet-stream'},     'reason': 'OK'}
     196608 of 548986    35% in    1s   156.72 kB/sDEBUG: ConnMan.put(): connection put back to pool (https://      bucket.s3.amazonaws.com#1)
     548986 of 548986   100% in    1s   415.92 kB/s  done
    DEBUG: ReceiveFile: Computed MD5 = 8123294dc33181f0ba8fe46442789f16
    DEBUG: DeUnicodising u'./part-r-00000.gz' using UTF-8
    DEBUG: set mtime to 1464876246.0

**Comment by thobrla** [comment]
Thanks, this is very useful.

The main differences that I see are:
1. gsutil is requesting a range (constituting the entire file), whereas s3cmd performs a generic GET
2. s3cmd disables SSL on the hostname check.  

It's not clear to me that either of these should be problematic though; gsutil does appear to be able to resolve the hostname, and everything else looks okay.  So I suspect that something is wrong in the boto library.

Could you try accessing the resource directly using [boto](https://github.com/boto/boto)?  If that also fails, we should file an issue there.

**Comment by julianvmodesto** [comment]
Ok, so I get Access Denied when accessing with boto, I think because it tries to get_bucket() first. I don't have access to get the location of the bucket, only the bucket + the subdirectory and its objects.

**Comment by thobrla** [comment]
That makes sense.  I think getting this fixed in boto is the path forward - can you create an issue there?

**Comment by julianvmodesto** [comment]
Sure thing!

**Comment by julianvmodesto** [comment]
Hey there, so I retried my boto call, and `get_bucket()` with `validate=False` works:

http://stackoverflow.com/a/27294557/1881379

**Comment by thobrla** [comment]
Thanks.  Do you know what in boto/gsutil is calling get_bucket with validate=True?  Based on your stack trace above, it seems like it is happening in the boto library but it's not obvious where, and I don't see any calls to get_bucket in s3/key.py.

Generally, I wouldn't expect gsutil to call get_bucket with validate=True unless you were doing something specifically with the bucket.

**Comment by julianvmodesto** [comment]
Looks like the default is validate=True for get_bucket() as well as storage_uri(): http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.connection.S3Connection.get_bucket

So maybe ListObjects in gslib/boto_translation.py
https://github.com/GoogleCloudPlatform/gsutil/blob/da2faac6f295c27a393c881e8012b6eb13beb30c/gslib/boto_translation.py#L346

which calls `bucket_uri = self._StorageUriForBucket(bucket_name)`

which calls `boto.storage_uri()`, with validate=True.

I think calling boto.storage_uri(validate=False) would be a fix:

https://github.com/GoogleCloudPlatform/gsutil/blob/da2faac6f295c27a393c881e8012b6eb13beb30c/gslib/boto_translation.py#L1038

**Comment by thobrla** [comment]
It should be fine to remove validation in that case.  If we do, I expect that only a subset of gsutil functionality will work with S3 user-specific directories, since we perform bucket listings for a variety of reasons (like determining if an object is a marker for a folder).

**Comment by thobrla** [comment]
https://github.com/GoogleCloudPlatform/gsutil/commit/9b68dae78247ba7fdc3313f06daf697e21d074d3 will be included in gsutil 4.21, so we'll be one step closer.

**Comment by thobrla** [comment]
gsutil 4.21 released standalone and PyPI versions today which include the validate=False fix, and the gcloud-bundled release should be available sometime within the next couple weeks.

**Comment by diclophis** [comment]
Would this bug also exhibit itself as an apparent 40gb limit of file uploads?

**Comment by thobrla** [comment]
No, I don't believe so.  `gsutil` doesn't support multi-part uploads to s3, though, so there is a 5GB limit per file, which you should get a warning for if you exceed.

**Comment by diclophis** [comment]
Ok, thanks, we found our problem was related to the lack of a `DescribeAcl` permission when the file size was over 40gb
