### ISSUE TITLE
gsutil with parallel_download repeatedly fails

### ISSUE THREAD

**Issue by georgeg0** [GoogleCloudPlatform/gsutil#385]
We are using gsutil version: 4.21 for downloading a 5TB file. User is using google sdk that is downloaded to his home directory for doing this transfer. Following is the command that we are using:
gsutil -m cp -r gs://my-bucket/bucketfolder /tmp/sciencefiles

Everytime we are running it starts the transfer but after a min we end up getting this. 

[Errno 104] Connection reset by peer
[Errno 104] Connection reset by peer
Process SyncManager-1:
Traceback (most recent call last):
  File "/opt/python2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/python2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
[Errno 2] No such file or directory
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
Exception in UIThread: [Errno 104] Connection reset by peer
[Errno 32] Broken pipe
    server.serve_forever()
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/opt/python2/lib/python2.7/threading.py", line 736, in start
Process Process-87:
Traceback (most recent call last):
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "google-cloud-sdk/platform/gsutil/gslib/command.py", line 2050, in run
    cls.logger = CreateGsutilLogger(cls.command_name)
AttributeError: 'NoneType' object has no attribute 'command_name'
  File "/opt/python2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap

```
self.run()
```

  File "/opt/python2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "google-cloud-sdk/platform/gsutil/gslib/command.py", line 1658, in _ApplyThreads
    _start_new_thread(self.__bootstrap, ())
[Errno 104] Connection reset by peer
error: can't start new thread
[Errno 2] No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "google-cloud-sdk/platform/gsutil/gslib/command.py", line 2053, in run
    self.PerformTask(task, cls)
  File "google-cloud-sdk/platform/gsutil/gslib/command.py", line 2038, in PerformTask
    num_done = caller_id_finished_count.Increment(caller_id, 1)
  File "google-cloud-sdk/platform/gsutil/gslib/parallelism_framework_util.py", line 91, in Increment
    return val
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 993, in __exit__
    return self._callmethod('release')
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

```
status_queue=status_queue)
```

  File "google-cloud-sdk/platform/gsutil/gslib/command.py", line 1952, in **init**
    worker_thread.start()
  File "/opt/python2/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "google-cloud-sdk/platform/gsutil/gslib/command.py", line 2049, in run
    cls = copy.copy(class_map[caller_id])
  File "<string>", line 2, in __getitem__
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 879, in RebuildProxy
    return func(token, serializer, incref=incref, **kwds)
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 733, in __init__
    self._incref()
  File "/opt/python2/lib/python2.7/multiprocessing/managers.py", line 783, in _incref
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/opt/python2/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/opt/python2/lib/python2.7/multiprocessing/connection.py", line 308, in SocketClient
    s.connect(address)
  File "/opt/python2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno [Errno 2] No such file or directory] <function RebuildProxy at 0x7f2a6db45050>: (<class 'multiprocessing.managers.AcquirerProxy'>, Token(typeid='Lock', address='/tmp/pymp-YWO6eC/listener-pqcWTG', id='7f2a6de1e3b0'), 'pickle', {})

**Comment by thobrla** [comment]
It looks like there is a resource issue starting new threads.  What operating system are you using?  Can you try reducing `parallel_process_count` and `parallel_thread_count` in your .boto configuration file?

If that doesn't work, you can fall back to single-threaded mode just for helping diagnose this issue:

`gsutil -o 'GSUtil:sliced_object_download_threshold=0' cp -r gs://my-bucket/bucketfolder /tmp/sciencefiles`

This will go slowly but hopefully will avoid the issue.

**Comment by georgeg0** [comment]
Thanks thobrla for replying to this. We are using centos. I could find .boto in user home directory(Is this what you referring to?) . But all those are commented out right now. We need to do it parallel to make it faster. If its commented out then what value it is using now ?

**Comment by thobrla** [comment]
Yes, I'm referring to `~/.boto`.  The default values for Linux are 1 process per core, 5 threads per process.

I think it would be useful to try reducing those numbers, and if that fails, running it once single-threaded for diagnostic purposes.

**Comment by georgeg0** [comment]
It did work after specifying .boto with 5 thread and 1 process. Not sure what it was taking by default.
Is there any other parameters apart from parallel_thread_count and parallel_process_count to make it more faster? Trying to achieve maximum download speed since we will be downloading PB's of data.

**Comment by thobrla** [comment]
Tuning `parallel_process_count` and `parallel_thread_count` are the most important parameters.  For downloads, you can also tune `sliced_object_download_max_components` which controls the maximum number of parallel streams used to download a single large file.

Out of curiosity, is your /tmp directory on a network file system or highly contended?  It's unusual for Python core multiprocessing modules to fail in this fashion.

**Comment by georgeg0** [comment]
Its on network file system, still the reason why it fails is unknown. Only thing which i can think of is it might be using some other numbers other than 5 threads and 1 process. The reason being after specifying same default its working fine. One other thing that we noticed is when downloading a big file the md5 is not calculated (field is empty) in the manifest file. How can we check the integrity of the file downloaded?

**Comment by thobrla** [comment]
Could you ask the file md5 question on StackOverflow (so others can easily search for the answer)?  It's tangential to this issue.

Having /tmp on a network file system is not ideal for gsutil - can you try setting it to something local via the TEMP environment variable?  That may help with the original issue and allow you to use a larger number of processes and threads.

**Comment by georgeg0** [comment]
But that is a requirement for us in having the data in nfs. The same data need to be accessed from different computing nodes.

**Comment by thobrla** [comment]
There's no problem with the download target being on NFS, but why does that necessitate that TEMP must point to NFS during gsutil execution?

**Comment by georgeg0** [comment]
I got what you are saying. The mount point is /sciencefiles. The /tmp/sciencefiles is just for testing after the first fail to /sciencefiles (it was populating with all _.gstmp files).

**Comment by thobrla** [comment]
My point is that the /tmp directory is getting used for file locking that is used to coordinate multiprocessing.  From your original issue:

"error: [Errno [Errno 2] No such file or directory] : (, Token(typeid='Lock', address='/tmp/pymp-YWO6eC/listener-pqcWTG', id='7f2a6de1e3b0'), 'pickle', {})"

If you point TEMP at a higher performing (non-network) file system, I suspect you'll have fewer issues with multiprocessing and be able to increase your `parallel_process_count` and `parallel_thread_count`.

**Comment by georgeg0** [comment]
Okay i got your point. I was confused with the download target and /tmp. Thanks for your recommendation.
