### ISSUE TITLE
Does not work binary complied with pyinstaller

### ISSUE THREAD

**Issue by rombr** [GoogleCloudPlatform/gsutil#407]
Hello, I need binary version of gsutil for using in system without python.
```
gsutil==4.20
pyinstaller==3.1.1
```
I use pyinstaller for compile.
```
ln -s `pwd`/env/bin/gsutil `pwd`/env/bin/gsutil.py
env/bin/pyinstaller --onefile env/bin/gsutil.py
```
And it is successfully compiled.

But when I try to run I get an error:
```
$ dist/gsutil 
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/home/user/env/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/gslib/__init__.py", line 109, in <module>
  File "site-packages/gslib/__init__.py", line 104, in _GetFileContents
  File "pkgutil.py", line 591, in get_data
  File "/home/user/env/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 474, in get_data
    with open(path, 'rb') as fp:
IOError: [Errno 2] No such file or directory: '/tmp/_MEIhMnGA3/gslib/VERSION'
gsutil returned -1
```
How can I fix it?

Thanks!

**Comment by houglum** [comment]
We don't actively support running or installing via pyinstaller, and admittedly I don't know very much about it.  Looking in `gslib/__init__.py`, we make some assumptions on where certain files are located based on the installation methods we support; these assumptions may not hold true when attempting to install via other methods.

But, at first glance, I think I can point you in the right direction.  Looking at the error message, it's apparently looking for the `gslib/VERSION` file.  When you install gsutil from tarball/zip or clone the repo from GitHub, this file is not present.  It it present, however, when you install via pip.  I assume you're trying to package some version that wasn't pip-installed, or you've somehow deleted the `gslib/VERSION` file.  Based on the last couple code blocks in `gslib/__init__.py`, it looks like you could try manually copying gsutil's `CHECKSUM` and `VERSION` files (for the appropriate version you're using, which I assume is 4.20 based on your issue description) to the `gslib` directory you're trying to package up with PyInstaller, then re-running PyInstaller.

**Comment by rombr** [comment]
I used pip in virtualenv and VERSION and CHECKSUM are there
```
$ tree env/lib/python2.7/site-packages/gsutil-4.20.dist-info/
env/lib/python2.7/site-packages/gsutil-4.20.dist-info/
├── dependency_links.txt
├── DESCRIPTION.rst
├── entry_points.txt
├── INSTALLER
├── METADATA
├── metadata.json
├── RECORD
├── top_level.txt
├── WHEEL
└── zip-safe

0 directories, 10 files

$ls -l env/lib/python2.7/site-packages/gslib/
total 952
-rw-r--r-- 1 rombr rombr  12537 Feb  1 12:57 aclhelpers.py
drwxr-xr-x 2 rombr rombr   4096 Feb  1 14:35 addlhelp
-rw-r--r-- 1 rombr rombr  24336 Feb  1 12:57 boto_resumable_upload.py
-rw-r--r-- 1 rombr rombr  73525 Feb  1 12:57 boto_translation.py
-rw-r--r-- 1 rombr rombr   3881 Feb  1 12:57 bucket_listing_ref.py
-rw-r--r-- 1 rombr rombr   4086 Feb  1 12:57 cat_helper.py
-rw-r--r-- 1 rombr rombr     33 Feb  1 12:57 CHECKSUM
-rw-r--r-- 1 rombr rombr  20232 Feb  1 12:57 cloud_api_delegator.py
-rw-r--r-- 1 rombr rombr   2956 Feb  1 12:57 cloud_api_helper.py
-rw-r--r-- 1 rombr rombr  27640 Feb  1 12:57 cloud_api.py
-rw-r--r-- 1 rombr rombr   3698 Feb  1 12:57 command_argument.py
-rw-r--r-- 1 rombr rombr  92977 Feb  1 12:57 command.py
-rw-r--r-- 1 rombr rombr  16583 Feb  1 12:57 command_runner.py
drwxr-xr-x 2 rombr rombr   4096 Feb  1 14:35 commands
-rw-r--r-- 1 rombr rombr 140452 Feb  1 12:57 copy_helper.py
-rw-r--r-- 1 rombr rombr    908 Feb  1 12:57 cred_types.py
-rw-r--r-- 1 rombr rombr   3278 Feb  1 12:57 cs_api_map.py
-rw-r--r-- 1 rombr rombr  12909 Feb  1 12:57 daisy_chain_wrapper.py
drwxr-xr-x 2 rombr rombr   4096 Feb  1 12:58 data
-rw-r--r-- 1 rombr rombr   1625 Feb  1 12:57 devshell_auth_plugin.py
-rw-r--r-- 1 rombr rombr   3614 Feb  1 12:57 encryption_helper.py
-rw-r--r-- 1 rombr rombr   2961 Feb  1 12:57 exception.py
-rw-r--r-- 1 rombr rombr   3350 Feb  1 12:57 file_part.py
-rw-r--r-- 1 rombr rombr  74704 Feb  1 12:57 gcs_json_api.py
-rw-r--r-- 1 rombr rombr   9909 Feb  1 12:57 gcs_json_credentials.py
-rw-r--r-- 1 rombr rombr  23887 Feb  1 12:57 gcs_json_media.py
-rw-r--r-- 1 rombr rombr  17307 Feb  1 12:57 hashing_helper.py
-rw-r--r-- 1 rombr rombr   3327 Feb  1 12:57 help_provider.py
-rw-r--r-- 1 rombr rombr   4658 Feb  1 12:57 __init__.py
-rw-r--r-- 1 rombr rombr  11047 Feb  1 12:57 ls_helper.py
-rw-r--r-- 1 rombr rombr  28906 Feb  1 12:57 __main__.py
-rw-r--r-- 1 rombr rombr  25519 Feb  1 12:57 name_expansion.py
-rw-r--r-- 1 rombr rombr   1093 Feb  1 12:57 no_op_auth_plugin.py
-rw-r--r-- 1 rombr rombr    950 Feb  1 12:57 no_op_credentials.py
-rw-r--r-- 1 rombr rombr   3459 Feb  1 12:57 parallelism_framework_util.py
-rw-r--r-- 1 rombr rombr  11497 Feb  1 12:57 parallel_tracker_file.py
-rw-r--r-- 1 rombr rombr   4057 Feb  1 12:57 plurality_checkable_iterator.py
-rw-r--r-- 1 rombr rombr   7203 Feb  1 12:57 progress_callback.py
-rw-r--r-- 1 rombr rombr   1149 Feb  1 12:57 project_id.py
-rw-r--r-- 1 rombr rombr    378 Feb  1 12:57 README
-rw-r--r-- 1 rombr rombr   8165 Feb  1 12:57 resumable_streaming_upload.py
-rw-r--r-- 1 rombr rombr   4642 Feb  1 12:57 seek_ahead_thread.py
-rw-r--r-- 1 rombr rombr   5457 Feb  1 12:57 sig_handling.py
-rw-r--r-- 1 rombr rombr   1936 Feb  1 12:57 storage_uri_builder.py
-rw-r--r-- 1 rombr rombr  10010 Feb  1 12:57 storage_url.py
-rw-r--r-- 1 rombr rombr  10870 Feb  1 12:57 tab_complete.py
drwxr-xr-x 4 rombr rombr   4096 Feb  1 14:35 tests
drwxr-xr-x 3 rombr rombr   4096 Feb  1 14:35 third_party
-rw-r--r-- 1 rombr rombr  20931 Feb  1 12:57 tracker_file.py
-rw-r--r-- 1 rombr rombr  34228 Feb  1 12:57 translation_helper.py
-rw-r--r-- 1 rombr rombr  50503 Feb  1 12:57 util.py
-rw-r--r-- 1 rombr rombr      4 Feb  1 12:57 VERSION
-rw-r--r-- 1 rombr rombr  31861 Feb  1 12:57 wildcard_iterator.py

$ cat env/lib/python2.7/site-packages/gslib/VERSION 
4.20

$ cat env/lib/python2.7/site-packages/gslib/CHECKSUM
ac4c5b3604d4e82fb7258f9cf012ebac

```

Anyway great thanks for your answer!

**Comment by houglum** [comment]
I spent a bit looking into how PyInstaller works today and tinkering with it.  Because we rely so heavily on having files organized in a certain hierarchy, being able to read from those files at runtime, and do so many dynamic imports (e.g. all the Command subclasses are dynamically imported, and AFAICT PyInstaller doesn't even bother including them in the executable), I don't think PyInstaller will be able to create a working executable for gsutil.

**Comment by rombr** [comment]
ok, thanks for your time
