### ISSUE TITLE
gsutil requires existing linux user

### ISSUE THREAD

**Issue by audriusKV** [GoogleCloudPlatform/gsutil#422]
When running `gsutil`with pid for which is no user created, then `gsutils` fails
```
+ gsutil cp -m -o 'gs://someUrl/**' .
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/opt/google-cloud-sdk/platform/gsutil/gsutil.py", line 113, in RunMain
    sys.exit(gslib.__main__.main())
  File "/opt/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 245, in main
    command_runner = CommandRunner()
  File "/opt/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 130, in __init__
    self.command_map = self._LoadCommandMap()
  File "/opt/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 136, in _LoadCommandMap
    __import__('gslib.commands.%s' % module_name)
  File "/opt/google-cloud-sdk/platform/gsutil/gslib/commands/test.py", line 44, in <module>
    from gslib.tests.util import GetTestNames
  File "/opt/google-cloud-sdk/platform/gsutil/gslib/tests/util.py", line 50, in <module>
    USER_NAME = pwd.getpwuid(USER_ID).pw_name
KeyError: 'getpwuid(): uid not found: 167'
```

This situation happens when Jenkins jobs are executed on Docker workers. Is it possible to workaround this issues?

**Comment by thobrla** [comment]
Thanks for the report.  There are two issues here:
1. getpwuid is being called at import time.  It should be lazily loaded.
2. How to respond when Linux user does not exist.  This likely invalidates some of the POSIX preservation tests, so my inclination is just to let this raise in those cases.
