### ISSUE TITLE
Cannot setmeta - Error: Invalid Argument

### ISSUE THREAD

**Issue by naveenbirru** [GoogleCloudPlatform/gsutil#512]
Gsutil setmeta command fails with error. Invalid Argument.

Trying to edit the existing meta data:
$**gsutil setmeta -h "x-goog-meta-opts:helloworld" gs://<object path>**
Setting metadata on gs://<object name>
BadRequestException: 400 InvalidArgument
<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message></Error>

Adding new metadata works well with cp command. (this test resolves any authentication related issues).
 $**gsutil -h "x-goog-meta-opts:earth" cp <filename> gs://<path>**
Copying file: [Content-Type=text/plain]...
\ [1 files][ 10.0 MiB/ 10.0 MiB]
Operation completed over 1 objects/10.0 MiB.

Here is the debug trace:
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File " gsutil/gslib/__main__.py", line 571, in _RunNamedCommandAndHandleExceptions
        user_project=user_project)
      File " gsutil/gslib/command_runner.py", line 319, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File " gsutil/gslib/commands/setmeta.py", line 206, in RunCommand
        seek_ahead_iterator=seek_ahead_iterator)
      File " gsutil/gslib/command.py", line 1383, in Apply
        arg_checker, should_return_results, fail_on_error)
      File " gsutil/gslib/command.py", line 1454, in _SequentialApply
        worker_thread.PerformTask(task, self)
      File " gsutil/gslib/command.py", line 2120, in PerformTask
        results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
      File " gsutil/gslib/commands/setmeta.py", line 128, in _SetMetadataFuncWrapper
        cls.SetMetadataFunc(name_expansion_result, thread_state=thread_state)
      File " gsutil/third_party/retry-decorator/retry_decorator/retry_decorator.py", line 20, in f_retry
        return f(*args, **kwargs)
      File " gsutil/gslib/commands/setmeta.py", line 261, in SetMetadataFunc
        provider=exp_src_url.scheme, fields=['id'])
      File " gsutil/gslib/cloud_api_delegator.py", line 261, in PatchObjectMetadata
        generation=generation, preconditions=preconditions, fields=fields)
      File " gsutil/gslib/boto_translation.py", line 702, in PatchObjectMetadata
        generation=generation)
      File " gsutil/gslib/boto_translation.py", line 1502, in _TranslateExceptionAndRaise
        raise translated_exception
    BadRequestException: BadRequestException: 400 InvalidArgument
    <?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message></Error>

BadRequestException: 400 InvalidArgument
<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message></Error>

**Comment by houglum** [comment]
I assume you've redacted your bucket and object name above, and that `gs://` was actually `gs://<bucket-name>/<object-name>` when you ran those commands, as the setmeta command fails if you don't supply an object URI.

I can't reproduce this on version 4.30 of gsutil, after having tried with both the XML and JSON APIs. So, that raises a few questions:

- What version of gsutil are you using?  If it's not 4.30, can you update and see if you can reproduce this with 4.30?
- In the example above, it looks like you're using the XML API (since this is coming from the XML API client class, boto_translation.py). Does this also happen when using the JSON API?  You can test this by running `gsutil -o "GSUtil:prefer_api=json" setmeta -h "x-goog-meta-opts:helloworld" gs://BUCKET/OBJECT`, assuming you're not using hmac credentials which are only compatible with the XML API.
- Does this only happen to objects that already have metadata attributes set (maybe they contain some invalid characters or have ended up in some odd state)? What about a newly-written object with no custom metadata?
