### ISSUE TITLE
rsync terminates with ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by hyperknot** [GoogleCloudPlatform/gsutil#574]
I'm running gsutil rsync in an Ubuntu 16.04 LTS Docker container. It's installed via the official command:

```
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install google-cloud-sdk -y
```

I have a bucket with 900k files. gsutil cp -r worked in both directions. gsutil rsync however cannot do this task, it terminates after a while with:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/seek_ahead_thread.py", line 97, in run
    for seek_ahead_result in self.seek_ahead_iterator:
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1149, in __iter__
    for diff_to_apply in self.cloned_diff_iterator:
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1057, in __iter__
    self._ParseTmpFileLine(self.sorted_src_urls_it.next()))
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 65, in _PopulateHead
    e = self.base_iterator.next()
ValueError: I/O operation on closed file
```

The command I've run was:
```
gsutil -m rsync -rdn /local/folder gs://bucket_name
```

**Comment by chapmanjacobd** [comment]
did you ever figure out why this happens?

just encountered this with

gsutil version: 5.8

**Comment by jasperjonker** [comment]
I have encountered the same issue. I'm copying a large filesystem (~1TB) to a google bucket.

- Running in docker container `gcr.io/google.com/cloudsdktool/google-cloud-cli:slim`. Image ID `756954bf070c`.
- Running the command `/usr/bin/gsutil -m rsync -r "/folder/to/copy" "gs://$google_bucket"`
- It gives me this error about halfway, after having copied a lot of GBs already.

Logs:
```sh
Copying file:///mnt/Production_NAS/20190925_201722_00002.txt [Content-Type=text/plain]...
CommandException: 3 files/objects could not be copied/removed.
Exception in thread Thread-5:9.5 GiB]   94.8 MiB/s ETA -1:59:55
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/bundledpythonunix/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/seek_ahead_thread.py", line 102, in run
    for seek_ahead_result in self.seek_ahead_iterator:
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1311, in __iter__
    for diff_to_apply in self.cloned_diff_iterator:
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1212, in __iter__
    src_md5) = (self._ParseTmpFileLine(next(self.sorted_src_urls_it)))
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 96, in __next__
    raise six.reraise(item_tuple[1].__class__, item_tuple[1], item_tuple[2])
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/six/six.py", line 693, in reraise
    raise value
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 70, in _PopulateHead
    e = next(self.base_iterator)
ValueError: I/O operation on closed file.
^C
```

**Comment by chapmanjacobd** [comment]
did you try with

```
/usr/bin/gsutil rsync -ru "/folder/to/copy" "gs://$google_bucket"
```

if most of the files are already copied it doesn't need to copy again
