### ISSUE TITLE
parse of /etc/os-release can't handle blank lines and comments

### ISSUE THREAD

**Issue by buczek** [GoogleCloudPlatform/gsutil#655]
https://github.com/GoogleCloudPlatform/gsutil/blob/4706acb54be166c1f95d96de6c1e9aa772d16e93/gslib/utils/parallelism_framework_util.py#L251

According to http://www.freedesktop.org/software/systemd/man/os-release.html, `/etc/os-release` may contain comment lines and blank lines which are to be ignored.

When `gsutil help` is run with a /etc/os-release of
```
# see http://www.freedesktop.org/software/systemd/man/os-release.html

NAME=MarIuX64
ID=mariux64
VERSION=2.0
VERSION_ID=2.0
PRETTY_NAME="MarIuX64 2.0 GNU/Linux 2010-2012"
ANSI_COLOR="1;34"
```
a parse error is thrown:
```
buczek@theinternet:~$ gsutil help
Traceback (most recent call last):
  File "/home/buczek/.local/bin/gsutil", line 11, in <module>
    sys.exit(main())
  File "/home/buczek/.local/lib/python2.7/site-packages/gslib/__main__.py", line 212, in main
    if (gslib.utils.parallelism_framework_util
  File "/home/buczek/.local/lib/python2.7/site-packages/gslib/utils/parallelism_framework_util.py", line 297, in CheckMultiprocessingAvailableAndInit
    should_prohibit_multiprocessing, os_name = ShouldProhibitMultiprocessing()
  File "/home/buczek/.local/lib/python2.7/site-packages/gslib/utils/parallelism_framework_util.py", line 251, in ShouldProhibitMultiprocessing
    os_name = f.read().split('\n')[0].split('=')[1].strip('"')
IndexError: list index out of range
```
because the code wrongly assumes, that the first line of the file contains a variable assignment.

**Comment by walkerjoe** [comment]
This issue is resolved and the fix has been added to main: https://github.com/GoogleCloudPlatform/gsutil/pull/656
