### ISSUE TITLE
Getting AttributeError when running gsutil

### ISSUE THREAD

**Issue by rlarner-quizlet** [GoogleCloudPlatform/gsutil#676]
This just started happening today when I try to run `gsutil`:
```
Traceback (most recent call last):
  File "/usr/lib64/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 13, in <module>
    import bootstrapping
  File "/usr/lib64/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 32, in <module>
    import setup  # pylint:disable=g-import-not-at-top
  File "/usr/lib64/google-cloud-sdk/bin/bootstrapping/setup.py", line 66, in <module>
    DoAllRequiredChecks()
  File "/usr/lib64/google-cloud-sdk/bin/bootstrapping/setup.py", line 62, in DoAllRequiredChecks
    properties.VALUES.core.allow_py3.GetBool()):
AttributeError: '_SectionCore' object has no attribute 'allow_py3'
```
my version of python:
```
python --version
Python 2.7.5
```

gcloud version:
```
gcloud version
INFO: Display format "flattened[no-pad,separator=" "]".
Google Cloud SDK 238.0.0
alpha 2019.03.08
beta 2019.03.08
bq 2.0.42
bq-nix 2.0.42
core 2019.03.08
core-nix 2019.03.08
gcloud
gcloud-deps 2019.03.08
gcloud-deps-linux-x86_64 2019.03.08
gcloud-man-pages
gcloud-man-pages-nix 2019.03.08
gsutil 4.37
gsutil-nix 4.37
kubectl 2019.03.08
```

Any ideas what may be causing it?

**Comment by houglum** [comment]
Interesting -- that's something in the Cloud SDK code (their bootstrapping code runs before they actually invoke the "real" gsutil).  I just updated to the new gcloud SDK (from 235.0.0 to 238.0.0), and I don't get that error.  Although, it looks like my core config has that `allow_py3` value present:

```
$ gcloud config get-value core/allow_py3
True
```

You could try running this so that the value is present in your config:

```
$ gcloud config set core/allow_py3 True
```

**Comment by marceloganin** [comment]
Hello, I have the same problem. Can you help me?

Traceback (most recent call last):
  File "/root/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 13, in <module>
    import bootstrapping
  File "/root/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/root/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 36, in <module>
    from googlecloudsdk.core import yaml
  File "/root/google-cloud-sdk/lib/googlecloudsdk/core/yaml.py", line 31, in <module>
    from googlecloudsdk.core import yaml_location_value
  File "/root/google-cloud-sdk/lib/googlecloudsdk/core/yaml_location_value.py", line 39, in <module>
    from ruamel import yaml
  File "/usr/lib64/python2.7/site-packages/ruamel/yaml/__init__.py", line 81, in <module>
    from ruamel.yaml.main import *  # NOQA
  File "/usr/lib64/python2.7/site-packages/ruamel/yaml/main.py", line 6, in <module>
    from typing import List, Set, Dict, Tuple, Optional, Union, BinaryIO, IO, Any  # NOQA
ImportError: No module named typing

-----------
python --version
Python 2.7.13
-----------
gcloud version
Google Cloud SDK 272.0.0
bq 2.0.50
core 2019.11.16
gsutil 4.46
-----------

thanks!

**Comment by thomasmaclean** [comment]
This seems to be an unrelated issue. The short term fix would just be to run `sudo pip install typing`.

**Comment by bw2** [comment]
Also seeing this error after adding -n option to  gsutil -m cp. 

gsutil v4.52 and Python 2.7.16
