### ISSUE TITLE
gsutil on python 3.6 - cannot authenticate

### ISSUE THREAD

**Issue by mvanelk** [GoogleCloudPlatform/gsutil#751]
Great to see support for Python 3!

Went and tried it out using `pip install git+https://github.com/GoogleCloudPlatform/gsutil.git`

It installs ok, I can call it without any errors, but when I go through the authentication procedure (go to URL, authorise, copy token, paste in CLI) I get the following error: 

```
Traceback (most recent call last):
  File "{CONDA_ENV_PATH}/bin/gsutil", line 10, in <module>
    sys.exit(main())
  File "{CONDA_ENV_PATH}/lib/python3.6/site-packages/gslib/__main__.py", line 420, in main
    perf_trace_token=perf_trace_token, user_project=user_project)
  File "{CONDA_ENV_PATH}/lib/python3.6/site-packages/gslib/__main__.py", line 734, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "{CONDA_ENV_PATH}/lib/python3.6/site-packages/gslib/__main__.py", line 604, in _RunNamedCommandAndHandleExceptions
    user_project=user_project)
  File "{CONDA_ENV_PATH}/lib/python3.6/site-packages/gslib/command_runner.py", line 391, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "{CONDA_ENV_PATH}/lib/python3.6/site-packages/gslib/commands/config.py", line 1300, in RunCommand
    configure_auth=configure_auth)
  File "{CONDA_ENV_PATH}/lib/python3.6/site-packages/gslib/commands/config.py", line 1082, in _WriteBotoConfigFile
    % (host_key, host_key))
TypeError: not enough arguments for format string`
```

If I insert a print statement in the code, host_key is apparently 's3'.

I can fall back to other methods for now, but love the simplicity of the gsutil commands, would be great if there's a fix for this

**Comment by houglum** [comment]
Hm... the line numbers you have there don't match up with what's currently at the HEAD commit on our master branch -- permalink here:
https://github.com/GoogleCloudPlatform/gsutil/blob/63a3fe7f29d70505e226711ace11aaf392439faa/gslib/commands/config.py#L1082

Maybe you're running a different version of gsutil than the one you installed with your pip command?

**Comment by houglum** [comment]
Can you reproduce this with a fresh checkout from this repository? E.g.:

```
git clone https://github.com/GoogleCloudPlatform/gsutil.git gsutil-github
cd gsutil-github
git submodule update --init --recursive
./gsutil config <whatever params you used in your original command>
```

**Comment by mvanelk** [comment]
Great, that works! I can now authenticate using ```gsutil config``` without a problem. 

Thanks!
