### ISSUE TITLE
Py3 integration tests fail for GCE credentials during refresh

### ISSUE THREAD

**Issue by houglum** [GoogleCloudPlatform/gsutil#819]
Example failure is below, from Python 3.5.3 on Debian 9 GCE VM (the boto setting I changed was to make the `default_project_id` in `/etc/boto.cfg` have the project's ID, rather than its number) run with one of our 4.40 prerelease candidates.  I'm mostly adding this here for context when I submit the PR to apitools to fix this.

```
$ LC_ALL=en_US.UTF-8 python3 ./gsutil -m test -p 20 acl.TestAcl.test_acl_set_version_specific_uri acl.TestAclOldAlias.test_acl_set_version_specific_uri
Running 2 tests in parallel mode (2 processes).
Test process creation finished (2/2 created)
Results for failed test gslib.tests.test_acl.TestAcl.test_acl_set_version_specific_uri:
1/1 finished - E[0] F[0] s[0] - TestAcl.test_acl_set_version_specific_ur - E
======================================================================
ERROR: test_acl_set_version_specific_uri (gslib.tests.test_acl.TestAcl)
Tests setting an ACL on a specific version of an object.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/houglum/rchoug/gsutil/gslib/tests/test_acl.py", line 65, in setUp
self.CreateBucket().bucket_name, fields=['projectNumber']).projectNumber
File "/home/houglum/rchoug/gsutil/gslib/gcs_json_api.py", line 417, in GetBucket
global_params=global_params)
File "/home/houglum/rchoug/gsutil/gslib/third_party/storage_apitools/storage_v1_client.py", line 293, in Get
config, request, global_params=global_params)
File "/home/houglum/rchoug/gsutil/third_party/apitools/apitools/base/py/base_api.py", line 729, in _RunMethod
http, http_request, **opts)
File "/home/houglum/rchoug/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 356, in MakeRequest
max_retry_wait, total_wait_sec))
File "/home/houglum/rchoug/gsutil/gslib/utils/retry_util.py", line 65, in WarnAfterManyRetriesHandler
http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
File "/home/houglum/rchoug/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
raise retry_args.exc
File "/home/houglum/rchoug/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 346, in MakeRequest
check_response_func=check_response_func)
File "/home/houglum/rchoug/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 396, in _MakeRequestNoRetry
redirections=redirections, connection_type=connection_type)
File "/home/houglum/rchoug/gsutil/third_party/oauth2client/oauth2client/transport.py", line 159, in new_request
credentials._refresh(orig_request_method)
File "/home/houglum/rchoug/gsutil/third_party/apitools/apitools/base/py/credentials_lib.py", line 391, in _refresh
oauth2client.client.OAuth2Credentials._refresh(self, do_request)
File "/home/houglum/rchoug/gsutil/third_party/oauth2client/oauth2client/client.py", line 761, in _refresh
self._do_refresh_request(http)
File "/home/houglum/rchoug/gsutil/third_party/apitools/apitools/base/py/credentials_lib.py", line 410, in _do_refresh_request
credential_info = json.loads(content)
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by houglum** [comment]
After adding the change in https://github.com/google/apitools/pull/272, all tests pass using GCE credentials:

```
# To show which version of Python, which credentials files are being loaded, etc.:
$ LC_ALL=en_US.UTF-8 python3 ./gsutil -D version
# Only relevant lines were left in:
gsutil version: 4.40pre_rc13
boto version: 2.49.0
python version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
OS: Linux 4.9.0-9-amd64
using cloud sdk: False
pass cloud sdk credentials to gsutil: False
config path(s): /etc/boto.cfg, /home/houglum/.boto
config_file_list: ['/etc/boto.cfg', '/home/houglum/.boto']


$ cat ~/.boto
[GSUtil]
default_project_id=<REDACTED>  # Made this use the ID, not the number, of our test project.


$ LC_ALL=en_US.UTF-8 python3 ./gsutil -m test -p 25
Running 295 tests sequentially.
192/295 finished - E[0] F[0] s[0] - TestPerfDiagUnitTests.test_listing_d - WARNING: Argument `NAME` is deprecated. Use `--filter="name=( 'NAME' ... )"` instead.
295/295 finished - E[0] F[0] s[0] - FileIteratorTests.testRecursiveDirec - .
----------------------------------------------------------------------
Ran 295 tests in 11.742s

OK
Running 775 tests in parallel mode (25 processes). Please be patient
while your CPU is incinerated. If your machine becomes unresponsive,
consider reducing the amount of parallel test processes by running
'gsutil test -p <num_processes>'.
9/775 finished - 0 failures
[...]
774/775 finished - 0 failures
Parallel tests complete. Success: 775 Fail: 0
Ran 1070 tests in 553.025s (295 sequential in 11.789s, 775 parallel in 541.236s)

OK

```
