### ISSUE TITLE
gsutil rsync can't fetch files with a "+" in the name

### ISSUE THREAD

**Issue by philwo** [GoogleCloudPlatform/gsutil#833]
Problem: `gsutil rsync` can not download files that have a "+" in the name, because it seems to replace that character with a whitespace.

How to reproduce:
```
gsutil rsync -r gs://philwo-gsutil-test/ ~/gsutil-test/
```

Expected results: All files are downloaded.
Actual results: File with a "+" in the name is missing and an error is printed:

```
philwo@philwo-macbookpro2 ~/src/gsutil (master) rm -rf ~/gstest && mkdir ~/gstest && ./gsutil rsync -r gs://philwo-gsutil-test/ ~/gstest/
Building synchronization state...
Starting synchronization...
NotFoundException: 404 gs://philwo-gsutil-test/pl us does not exist.
```

As reference, this is how it looks in the Cloud console:
<img width="213" alt="Screenshot 2019-06-27 at 15 00 16" src="https://user-images.githubusercontent.com/504652/60268254-4c38b780-98ec-11e9-836f-5602db172b3a.png">

Broken with gsutil from HEAD (2bcb59fe0b45aea3d7329384de0c37f7ad4d6eb4).

**Comment by catleeball** [comment]
Thanks for reporting this, and sorry for the issue! I was able to reproduce the bug locally. I'll take a peek and see if we can squeeze in a fix before our next release. :slightly_smiling_face:

**Comment by philwo** [comment]
Thank you :)

**Comment by catleeball** [comment]
Stack trace from `python3 gsutil.py -D rsync . gs://do-not-delete-cball-test/`

```
Starting synchronization...
process count: 1
thread count: 1
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/usr/local/google/home/cball/gsutil/gslib/utils/copy_helper.py", line 3749, in PerformCopy
        src_obj_filestream = GetStreamFromFileUrl(src_url)
      File "/usr/local/google/home/cball/gsutil/gslib/utils/system_util.py", line 200, in GetStreamFromFileUrl
        return open(storage_url.object_name, mode)
    FileNotFoundError: [Errno 2] No such file or directory: './p s.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/google/home/cball/gsutil/gslib/__main__.py", line 626, in _RunNamedCommandAndHandleExceptions
        user_project=user_project)
      File "/usr/local/google/home/cball/gsutil/gslib/command_runner.py", line 411, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/usr/local/google/home/cball/gsutil/gslib/commands/rsync.py", line 1658, in RunCommand
        seek_ahead_iterator=seek_ahead_iterator)
      File "/usr/local/google/home/cball/gsutil/gslib/command.py", line 1515, in Apply
        arg_checker, should_return_results, fail_on_error)
      File "/usr/local/google/home/cball/gsutil/gslib/command.py", line 1586, in _SequentialApply
        worker_thread.PerformTask(task, self)
      File "/usr/local/google/home/cball/gsutil/gslib/command.py", line 2306, in PerformTask
        results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
      File "/usr/local/google/home/cball/gsutil/gslib/commands/rsync.py", line 1430, in _RsyncFunc
        preserve_posix=cls.preserve_posix_attrs)
      File "/usr/local/google/home/cball/gsutil/gslib/utils/copy_helper.py", line 3757, in PerformCopy
        raise CommandException(message)
    gslib.exception.CommandException: CommandException: Error opening file "file://./p s.txt": [Errno 2] No such file or directory: './p s.txt'.
    
CommandException: Error opening file "file://./p s.txt": [Errno 2] No such file or directory: './p s.txt'.
```

Stack trace from `python3 gsutil.py -D rsync ./p+s.txt gs://do-not-delete-cball-test/`

```
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/usr/local/google/home/cball/gsutil/gslib/__main__.py", line 626, in _RunNamedCommandAndHandleExceptions
        user_project=user_project)
      File "/usr/local/google/home/cball/gsutil/gslib/command_runner.py", line 411, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/usr/local/google/home/cball/gsutil/gslib/commands/rsync.py", line 1609, in RunCommand
        src_url = self._InsistContainer(self.args[0], False)
      File "/usr/local/google/home/cball/gsutil/gslib/commands/rsync.py", line 1592, in _InsistContainer
        url_str)
    gslib.exception.CommandException: CommandException: arg (./p+s.txt) does not name a directory, bucket, or bucket subdir.
    
CommandException: arg (./p+s.txt) does not name a directory, bucket, or bucket subdir.
```

Looks like this issue is present in release v4.39 as well as head of master branch

**Comment by catleeball** [comment]
Stack traces for those internal: http://gpaste/6650209041907712

**Comment by houglum** [comment]
Looks like a bug from when we did the big overhaul to change the code to support python 3.  The `_EncodeUrl` method used to use `quote_plus`:
https://github.com/GoogleCloudPlatform/gsutil/blob/d4b4a5c421fb56b2adbaf41076e9a3e86b3a3cb1/gslib/commands/rsync.py#L811

...but it's using `unquote_plus` now:
https://github.com/GoogleCloudPlatform/gsutil/blob/2bcb59fe0b45aea3d7329384de0c37f7ad4d6eb4/gslib/commands/rsync.py#L844

That's probably also responsible for https://github.com/GoogleCloudPlatform/gsutil/issues/806.
