### ISSUE TITLE
gsutil doesn't work with proxy on python3 

### ISSUE THREAD

**Issue by xEviL** [GoogleCloudPlatform/gsutil#880]
Tested the same setup with and without a proxy. Without a proxy it works. With a proxy I get this:
```
Traceback (most recent call last):
  File "/usr/local/bin/gsutil", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/gslib/__main__.py", line 431, in main
    user_project=user_project)
  File "/usr/local/lib/python3.6/site-packages/gslib/__main__.py", line 760, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "/usr/local/lib/python3.6/site-packages/gslib/__main__.py", line 626, in _RunNamedCommandAndHandleExceptions
    user_project=user_project)
  File "/usr/local/lib/python3.6/site-packages/gslib/command_runner.py", line 411, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/usr/local/lib/python3.6/site-packages/gslib/commands/ls.py", line 640, in RunCommand
    listing_helper.ExpandUrlAndPrint(storage_url))
  File "/usr/local/lib/python3.6/site-packages/gslib/utils/ls_helper.py", line 369, in ExpandUrlAndPrint
    print_initial_newline=False)
  File "/usr/local/lib/python3.6/site-packages/gslib/utils/ls_helper.py", line 443, in _RecurseExpandUrlAndPrint
    bucket_listing_fields=self.bucket_listing_fields):
  File "/usr/local/lib/python3.6/site-packages/gslib/wildcard_iterator.py", line 497, in IterAll
    expand_top_level_buckets=expand_top_level_buckets):
  File "/usr/local/lib/python3.6/site-packages/gslib/wildcard_iterator.py", line 173, in __iter__
    fields=bucket_listing_fields):
  File "/usr/local/lib/python3.6/site-packages/gslib/gcs_json_api.py", line 715, in ListObjects
    global_params=global_params)
  File "/usr/local/lib/python3.6/site-packages/gslib/third_party/storage_apitools/storage_v1_client.py", line 1217, in List
    config, request, global_params=global_params)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/base_api.py", line 729, in _RunMethod
    http, http_request, **opts)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/http_wrapper.py", line 356, in MakeRequest
    max_retry_wait, total_wait_sec))
  File "/usr/local/lib/python3.6/site-packages/gslib/utils/retry_util.py", line 65, in WarnAfterManyRetriesHandler
    http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/http_wrapper.py", line 346, in MakeRequest
    check_response_func=check_response_func)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/http_wrapper.py", line 396, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1953, in request
    cachekey,
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1524, in _conn_request
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1305, in connect
    sock.connect((self.host, self.port))
  File "/usr/local/lib/python3.6/site-packages/socks.py", line 406, in connect
    self.__negotiatehttp(destpair[0],destpair[1])
  File "/usr/local/lib/python3.6/site-packages/socks.py", line 357, in __negotiatehttp
    while resp.find("\r\n\r\n")==-1:
TypeError: a bytes-like object is required, not 'str'
```

`gsutil -D version` output:
```
gsutil version: 4.42
checksum: PACKAGED_GSUTIL_INSTALLS_DO_NOT_HAVE_CHECKSUMS (!= d901cf5a002200f4a5526a372681677c)
boto version: 2.49.0
python version: 3.6.9 (default, Jul 13 2019, 14:58:50) [GCC 8.3.0]
OS: Linux 4.4.0-142-generic
multiprocessing available: True
using cloud sdk: False
pass cloud sdk credentials to gsutil: False
config path(s): /usr/local/<redacted>/.boto
gsutil path: /usr/local/bin/gsutil
compiled crcmod: True
installed via package manager: True
editable install: False
Command being run: /usr/local/bin/gsutil -D version
config_file_list: ['/usr/local/<redacted>/.boto']
config: [('working_dir', '/mnt/pyami'), ('debug', '0'), ('proxy', 'REDACTED'), ('proxy_port', 'REDACTED'), ('https_validate_certificates', 'True'), ('working_dir', '/mnt/pyami'), ('debug', '0'), ('content_language', 'en'), ('default_api_version', '2'), ('default_project_id', '<redacted>')]
gsutil version: 4.42
```
`gsutil` is running in a Docker container made from `python-slim` base image and was installed using `pip install gsutil`.

**Comment by xEviL** [comment]
Tested additionally the same config in Python 2 setup, works with proxy as well.

**Comment by connorlwilkes** [comment]
I am having the same issue. I believe it is related to gsutil parsing the input of the port setting when it is originally set specifically as a str rather than a number - this is causing a type error.

**Comment by turribeach** [comment]
I am having a similar issue but the error I get is: 

`socks.HTTPError: (407, b'Proxy Authentication Required')`

I have  traced the problem to an update on Cloud SDK v296.0.0:

https://cloud.google.com/sdk/docs/release-notes#29600_2020-06-09

It seems to be the "Updated bundled Python executable to 3.7.5." line. In version 295.0.0 or below the bundled Python used by gsutil is v2.7.13 so gsutil seems to break on Python 3.7.5.

To verify this issue:

1. Run "gcloud --version" to verify your Google Cloud SDK is 295.0.0 or earlier
2. Then confirm "gsutil ls" runs fine using your proxy settings
3. Then run "gcloud components update" to update your Google Cloud SDK to the latest version (likely to be 300.0.0 or above)
4. Now run "gsutil ls" again and you should get a "407 Proxy Authentication"

You can rollback to version 295.0.0 using this command: "gcloud components update --version 295.0.0"

You can also reproduce the problem setting the CLOUDSDK_GSUTIL_PYTHON variable to use a python3 interpreter like this:

set CLOUDSDK_GSUTIL_PYTHON=c:\[path to your python3 installation\python

As a workaround I was able to update the Google Cloud SDK to the latest version (300.0.0) and set CLOUDSDK_GSUTIL_PYTHON to point to the embedded Python 2 interpreter which allows gsutil to work fine:

set CLOUDSDK_GSUTIL_PYTHON=C:\[path to your Google SDK 300.0.0 install]\platform\bundledpython2\python
However Google claims on the [Google Cloud SDK release notes](https://cloud.google.com/sdk/docs/release-notes) that support for Python 2 will be removed on July 31st 2020 so presumably this work around will stop working.

**Comment by rmenegaux** [comment]
I have the exact same issue as @xEviL (gsutil version 4.52) and have not been able to work it through. Has anyone found a fix or workaround?
