### ISSUE TITLE
Crash in 'gsutil help metadata'

### ISSUE THREAD

**Issue by kkm000** [GoogleCloudPlatform/gsutil#932]
'gsutil help metadata' crashes consistently with the error

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 7114: ordinal not in range(128)

`gsutil help` for several other topics works. This is the only one that I found to make it go boom.

First spotted in v4.45; upgrade to 4.46 did not change the behavior. gsutil is installed as part of the Google Cloud SDK.

The bug is far from a show-stopper, but would be nice to have fixed.

Stack trace
```
$ gsutil help metadata
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil.py", line 124, in RunMain
    sys.exit(gslib.__main__.main())
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 433, in main
    user_project=user_project)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 762, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 628, in _RunNamedCommandAndHandleExceptions
    user_project=user_project)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 411, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/help.py", line 173, in RunCommand
    self._OutputHelp(''.join(output))
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/help.py", line 202, in _OutputHelp
    universal_newlines=True).communicate(input=help_str)
  File "/usr/lib/python2.7/subprocess.py", line 469, in communicate
    self.stdin.write(input)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 7114: ordinal not in range(128)
```
System/environment information
```
$ gsutil --version
gsutil version: 4.46
$ python2.7 --version
Python 2.7.16
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
$ uname -srvmo
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by kdambekalns** [comment]
Seeing this on macOS Catalina with gsutil version 4.47 and Python 2.7.16.

`CLOUDSDK_GSUTIL_PYTHON=python3 gsutil help metadata` works fine for me, too (Python 3.7.6). But other variations with setting locale don't help with Python 2.7.
